;;; luu-probe.el --- Local latency and lifecycle probes -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'json)
(require 'agent-shell-sidebar)

(defvar luu--metrics nil)

(defun luu--inc (key &optional amount)
  (puthash key (+ (gethash key luu--metrics 0) (or amount 1)) luu--metrics))

(defun luu--emit (kind values)
  (princ (concat "LUU " (json-encode (cons (cons 'kind kind) values)) "\n")))

(defun luu--write (root name)
  (let ((file (expand-file-name (concat ".agent-shell/transcripts/" name ".md") root)))
    (make-directory (file-name-directory file) t)
    (with-temp-file file
      (insert (format "# Agent Shell Transcript\n\n**Agent:** Claude\n**Started:** 2026-09-08 12:30:00\n**Working Directory:** %s\n**Session ID:** %s\n**Model:** test-model\n\n---\n\n## User (2026-09-08)\n\nPrompt %s\n" root name name)))
    file))

(defmacro luu--fixture (count &rest body)
  (declare (indent 1))
  `(let* ((root (file-name-as-directory (make-temp-file "/private/tmp/sidebar-luu-" t)))
          (default-directory root)
          (agent-shell-sidebar-extra-project-roots (list root))
          (agent-shell-sidebar-refresh-timer nil)
          (agent-shell-sidebar--parse-cache (make-hash-table :test 'equal))
          (projectile-known-projects nil)
          (agent-shell-sidebar-parse-chunk-size 30))
     (unwind-protect
         (cl-letf (((symbol-function 'project-known-project-roots) (lambda () nil))
                   ((symbol-function 'agent-shell-buffers) (lambda () nil)))
           (dotimes (i ,count) (luu--write root (format "%05d" i)))
           (with-temp-buffer
             (agent-shell-sidebar-mode)
             ,@body))
       (delete-directory root t))))

(defmacro luu--instrument (&rest body)
  (declare (indent 0))
  `(let ((luu--metrics (make-hash-table :test 'eq))
         (redraw (symbol-function 'agent-shell-sidebar--redraw))
         (parse (symbol-function 'agent-shell-sidebar--parse-header-from-file))
         (render (symbol-function 'agent-shell-sidebar--render-transcript-row))
         (collect (symbol-function 'agent-shell-sidebar--collect))
         (attrs (symbol-function 'file-attributes))
         (listdir (symbol-function 'directory-files-and-attributes)))
     (cl-letf (((symbol-function 'agent-shell-sidebar--redraw)
                (lambda ()
                  (let ((start (float-time)))
                    (prog1 (funcall redraw)
                      (luu--inc 'redraws)
                      (luu--inc 'redraw-ms (* 1000 (- (float-time) start)))))))
               ((symbol-function 'agent-shell-sidebar--parse-header-from-file)
                (lambda (file)
                  (let ((start (float-time)))
                    (prog1 (funcall parse file)
                      (luu--inc 'header-reads)
                      (luu--inc 'parse-ms (* 1000 (- (float-time) start)))))))
               ((symbol-function 'agent-shell-sidebar--render-transcript-row)
                (lambda (&rest args) (luu--inc 'rows) (apply render args)))
               ((symbol-function 'agent-shell-sidebar--collect)
                (lambda ()
                  (let ((start (float-time)))
                    (prog1 (funcall collect)
                      (luu--inc 'collections)
                      (luu--inc 'collect-ms (* 1000 (- (float-time) start)))))))
               ((symbol-function 'file-attributes)
                (lambda (&rest args) (luu--inc 'file-attributes-calls) (apply attrs args)))
               ((symbol-function 'directory-files-and-attributes)
                (lambda (&rest args) (luu--inc 'directory-scans) (apply listdir args))))
       ,@body)))

(defun luu--metric-values ()
  (let (values)
    (maphash (lambda (key value) (push (cons key value) values)) luu--metrics)
    (nreverse values)))

(defun luu--percentile (numbers fraction)
  (nth (max 0 (1- (ceiling (* fraction (length numbers)))))
       (sort (copy-sequence numbers) #'<)))

(defun luu--scale (count)
  (luu--fixture count
    (garbage-collect)
    (luu--instrument
      (let ((start (float-time))
            (gc-count gcs-done)
            (gc-seconds gc-elapsed)
            (memory-before (memory-use-counts))
            first-ms chunk-ms)
        (agent-shell-sidebar-refresh)
        (setq first-ms (* 1000 (- (float-time) start)))
        (while agent-shell-sidebar--parse-queue
          (let ((tick-start (float-time)))
            (agent-shell-sidebar--parse-tick)
            (push (* 1000 (- (float-time) tick-start)) chunk-ms)))
        (luu--emit
         "scale-cold"
         (append `((files . ,count)
                   (initial-refresh-ms . ,first-ms)
                   (elapsed-ms . ,(* 1000 (- (float-time) start)))
                   (tick-count . ,(length chunk-ms))
                   (tick-total-ms . ,(apply #'+ chunk-ms))
                   (tick-median-ms . ,(luu--percentile chunk-ms 0.5))
                   (tick-p95-ms . ,(luu--percentile chunk-ms 0.95))
                   (tick-max-ms . ,(apply #'max chunk-ms))
                   (gc-count . ,(- gcs-done gc-count))
                   (gc-ms . ,(* 1000 (- gc-elapsed gc-seconds)))
                   (conses-allocated . ,(- (car (memory-use-counts)) (car memory-before))))
                 (luu--metric-values)))))
    (dotimes (repeat 3)
      (luu--instrument
        (let ((start (float-time)))
          (agent-shell-sidebar-refresh)
          (cl-assert (null agent-shell-sidebar--parse-queue))
          (luu--emit "scale-warm"
                     (append `((files . ,count) (repeat . ,repeat)
                               (elapsed-ms . ,(* 1000 (- (float-time) start))))
                             (luu--metric-values))))))))

(defun luu--lifecycle ()
  (luu--fixture 120
    (luu--instrument
      (agent-shell-sidebar-refresh)
      (agent-shell-sidebar--parse-tick)
      (let ((remaining (length agent-shell-sidebar--parse-queue)))
        (agent-shell-sidebar-refresh)
        (cl-assert (= remaining (length agent-shell-sidebar--parse-queue)))
        (while agent-shell-sidebar--parse-queue (agent-shell-sidebar--parse-tick))
        (cl-assert (= 120 (gethash 'header-reads luu--metrics)))
        (luu--emit "refresh-during-parse"
                   (append `((remaining-before-refresh . ,remaining)
                             (pending-after-drain . ,(length agent-shell-sidebar--parse-queue)))
                           (luu--metric-values))))))
  (luu--fixture 120
    (save-window-excursion
      (let ((buffer (current-buffer)))
        (display-buffer-in-side-window buffer '((side . left)))
        (luu--instrument
          (agent-shell-sidebar-refresh)
          (agent-shell-sidebar-hide-sidebar)
          (cl-assert (null (get-buffer-window buffer t)))
          (let ((pending-before (length agent-shell-sidebar--parse-queue))
                (timer-before (timerp agent-shell-sidebar--parse-timer))
                (reads-before (gethash 'header-reads luu--metrics 0))
                (rows-before (gethash 'rows luu--metrics 0)))
            (agent-shell-sidebar--refresh-tick buffer)
            (cl-assert (= 1 (gethash 'collections luu--metrics)))
            (agent-shell-sidebar--parse-tick buffer)
            (luu--emit "hidden-parse"
                       `((visible . ,(and (get-buffer-window buffer t) t))
                         (timer-after-hide . ,timer-before)
                         (pending-before-hidden-tick . ,pending-before)
                         (pending-after-hidden-tick . ,(length agent-shell-sidebar--parse-queue))
                         (header-reads-while-hidden . ,(- (gethash 'header-reads luu--metrics 0) reads-before))
                         (rows-rendered-while-hidden . ,(- (gethash 'rows luu--metrics 0) rows-before))
                         (timer-after-hidden-tick . ,(timerp agent-shell-sidebar--parse-timer))))))))))

(defun luu--idle-reset ()
  (luu--fixture 1
    (let ((idle 0)
          (agent-shell-sidebar-refresh-timer 30)
          thresholds)
      (cl-letf (((symbol-function 'current-idle-time)
                 (lambda () (and idle (seconds-to-time idle)))))
        (agent-shell-sidebar--schedule-refresh)
        (push (float-time (timer--time agent-shell-sidebar--refresh-timer-object)) thresholds)
        (dotimes (_ 10)
          (setq idle (float-time (timer--time agent-shell-sidebar--refresh-timer-object)))
          (timer-event-handler agent-shell-sidebar--refresh-timer-object)
          (push (float-time (timer--time agent-shell-sidebar--refresh-timer-object)) thresholds))
        ;; Model command-loop input reset.  The real timer object retains its
        ;; threshold unless a registered hook or timer replaces it.
        (setq idle nil)
        (run-hooks 'post-command-hook)
        (setq idle 30)
        (luu--emit
         "idle-reset"
         `((refresh-interval-seconds . ,agent-shell-sidebar-refresh-timer)
           (continuous-idle-thresholds . ,(vconcat (nreverse thresholds)))
           (new-idle-period-seconds . ,idle)
           (stored-refresh-threshold-seconds . ,(float-time (timer--time agent-shell-sidebar--refresh-timer-object)))
           (eligible-in-new-idle-period . ,(not (time-less-p (current-idle-time) (timer--time agent-shell-sidebar--refresh-timer-object))))
           (method . "Real timer objects and timer-event-handler; mocked current-idle-time and post-command-hook input reset; no real keyboard or wall-clock wait")))))))

(luu--emit "environment"
           `((emacs . ,emacs-version)
             (system . ,system-configuration)
             (compiled-sidebar . ,(byte-code-function-p (symbol-function 'agent-shell-sidebar--parse-tick)))
             (gc-cons-threshold . ,gc-cons-threshold)
             (gc-cons-percentage . ,gc-cons-percentage)
             (chunk-size . ,agent-shell-sidebar-parse-chunk-size)
             (method . "Direct synchronous callbacks; fresh metadata cache; OS cache not flushed; instrumented counts and timing; idle delays and display redisplay excluded")))
(pcase (getenv "LUU_PROBE_CASE")
  ("lifecycle" (luu--lifecycle) (luu--idle-reset))
  (_ (luu--scale (string-to-number (or (getenv "LUU_PROBE_FILES") "300")))))
