;;; rename-tests.el --- Standalone namespace contract -*- lexical-binding: t; -*-
(require 'ert)
(require 'agent-sidebar)

(ert-deftest rename-loads-without-old-library-or-aliases ()
  (should-not (featurep 'agent-shell-sidebar))
  (should-not (locate-library "agent-shell-sidebar"))
  (should (eq (get 'agent-sidebar-mode 'derived-mode-parent) 'special-mode))
  (mapatoms
   (lambda (symbol)
     (when (string-prefix-p "agent-sidebar-" (symbol-name symbol))
       (should (eq (indirect-variable symbol) symbol))
       (when (fboundp symbol)
         (should-not (symbolp (symbol-function symbol))))))))

(ert-deftest rename-custom-buffer-name-and-width-drive-window ()
  (let ((agent-sidebar-name " *renamed sidebar custom name*")
        (agent-sidebar-width 37)
        (agent-sidebar-enabled-providers nil)
        (agent-sidebar-refresh-timer nil)
        (agent-sidebar-resize-on-open nil)
        (post-command-hook nil)
        (agent-sidebar--timer-buffers nil))
    (unwind-protect
        (save-window-excursion
          (agent-sidebar-show-sidebar)
          (let ((window (agent-sidebar--sidebar-window)))
            (should (window-live-p window))
            (should (eq (window-buffer window) (get-buffer agent-sidebar-name)))
            (should (= (window-total-width window) 37))
            (with-current-buffer (window-buffer window)
              (should (eq major-mode 'agent-sidebar-mode))
              (should (string-search "no chats found" (buffer-string)))))
          (agent-sidebar-hide-sidebar)
          (should-not (agent-sidebar-showing-sidebar-p)))
      (when-let* ((buffer (get-buffer agent-sidebar-name)))
        (kill-buffer buffer)))))

(ert-deftest rename-keymap-contains-only-new-sidebar-commands ()
  (dolist (binding '(("RET" . agent-sidebar-visit) ("o" . agent-sidebar-open-transcript)
                     ("/" . agent-sidebar-set-filter) ("g" . agent-sidebar-refresh)
                     ("q" . agent-sidebar-hide-sidebar) ("d" . agent-sidebar-mark-delete)
                     ("x" . agent-sidebar-execute) ("TAB" . agent-sidebar-toggle-group)
                     ("G" . agent-sidebar-set-grouping) ("N" . agent-sidebar-new-session)
                     ("A" . agent-sidebar-visit-in-agent-shell)))
    (should (eq (lookup-key agent-sidebar-mode-map (kbd (car binding))) (cdr binding)))))

(ert-deftest rename-buffer-state-and-timers-are-owned-and-cleaned ()
  (let ((first (generate-new-buffer " *rename first*"))
        (second (generate-new-buffer " *rename second*"))
        (agent-sidebar-refresh-timer 30)
        (agent-sidebar--timer-buffers nil)
        (post-command-hook nil)
        timer)
    (unwind-protect
        (progn
          (with-current-buffer first
            (agent-sidebar-mode)
            (should (local-variable-p 'agent-sidebar--parse-cache))
            (puthash "one" 'delete agent-sidebar--marks)
            (setq timer agent-sidebar--refresh-timer-object)
            (should (timerp timer)))
          (with-current-buffer second
            (agent-sidebar-mode)
            (should-not (gethash "one" agent-sidebar--marks)))
          (kill-buffer first)
          (should-not (memq timer timer-idle-list))
          (should-not (memq first agent-sidebar--timer-buffers)))
      (when (buffer-live-p first) (kill-buffer first))
      (when (buffer-live-p second) (kill-buffer second)))))
