;;; verify.el --- Check vendored autoloads and shared browser behavior -*- lexical-binding: t; -*-
(require 'cl-lib)
(require 'use-package)
(let* ((root "/Users/ducnguyen/.emacs.d/")
       (vendor (expand-file-name "vendor/vegeta/" root))
       (form (with-temp-buffer
               (insert-file-contents (expand-file-name "lisp/package-declarations.el" root))
               (goto-char (point-min))
               (re-search-forward "^(use-package vegeta")
               (goto-char (match-beginning 0))
               (read (current-buffer)))))
  ;; This is the vendor-directory setup used by init.el after package activation.
  (dolist (directory (directory-files (expand-file-name "vendor/" root) t "\\w+"))
    (when (file-directory-p directory) (add-to-list 'load-path directory)))
  (eval form t)
  (cl-assert (autoloadp (symbol-function 'vegeta-toggle-sidebar)))
  (cl-assert (equal (cadr (symbol-function 'vegeta-toggle-sidebar)) "vegeta"))
  (cl-assert (file-in-directory-p (locate-library "vegeta") vendor))
  (require 'vegeta)
  (cl-assert (featurep 'vegeta))
  (cl-assert (commandp 'vegeta-toggle-sidebar))
  (cl-assert (file-in-directory-p (symbol-file 'vegeta-toggle-sidebar 'defun) vendor))
  (message "Verified autoload and definition: %s" (symbol-file 'vegeta-toggle-sidebar 'defun))
  (setenv "GAP_PREFIX" "vegeta")
  (load (expand-file-name "agent/vegeta-gap-2026-09-08/gap-tests.el" root) nil t)
  (ert-run-tests-batch-and-exit "^gap-common-"))
