;;; -*- lexical-binding: t; -*-
(require 'cl-lib)
(require 'json)
(require 'fzfa)
(fzf-native-ensure-loaded)

(let* ((mode (or (getenv "PROBE_MODE") "continuous"))
       (query (or (getenv "PROBE_QUERY") ""))
       (limit (string-to-number (or (getenv "PROBE_LIMIT") "100")))
       (command (format "/usr/bin/python3 -u %s %s"
                        (shell-quote-argument
                         (expand-file-name "producer.py"
                                           (file-name-directory load-file-name)))
                        (shell-quote-argument mode)))
       (source (fzfa-make-source :command command))
       (handle (fzf-native-async-start command))
       (started (float-time))
       samples first-native first-fzfa done-time)
  (setf (fzfa-source-handle source) handle)
  (unwind-protect
      (while (and (< (- (float-time) started) 12)
                  (or (not done-time)
                      (< (- (float-time) started done-time) 0.15)))
        (let* ((output (fzfa--source-async-out source query limit))
               (snapshot (fzf-native-async-snapshot
                          handle (fzfa-source-request-id source)))
               (elapsed (- (float-time) started))
               (candidates (plist-get snapshot :candidates))
               (shown (eq (car-safe output) 'final))
               (done (plist-get snapshot :reader-done)))
          (when (and candidates (not first-native))
            (setq first-native elapsed))
          (when (and shown (nth 1 output) (not first-fzfa))
            (setq first-fzfa elapsed))
          (when (and done (not done-time))
            (setq done-time elapsed))
          (push `((seconds . ,elapsed)
                  (state . ,(plist-get snapshot :state))
                  (stale . ,(if (plist-get snapshot :stale) t :json-false))
                  (reader_done . ,(if done t :json-false))
                  (pool . ,(plist-get snapshot :pool-generation))
                  (result_pool . ,(plist-get snapshot :result-pool-generation))
                  (native_candidates . ,(length candidates))
                  (fzfa_output . ,(if (consp output) (car output) output))
                  (fzfa_candidates . ,(if shown (length (nth 1 output)) 0)))
                samples))
        (sleep-for 0.02))
    (fzf-native-async-stop handle))
  (princ
   (json-encode
    `((mode . ,mode) (query . ,query)
      (first_native . ,first-native)
      (first_fzfa . ,first-fzfa)
      (reader_done_at . ,done-time)
      (samples . ,(vconcat (nreverse samples)))))))
