;;; live-validation.el --- MELPA validation in the existing Emacs -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'package)
(require 'ert)

(defconst fzf-melpa-root "/private/tmp/fzf-melpa-validation-20260906/")
(defconst fzf-melpa-source "/private/tmp/fzf-native-melpa-license-notices/")

(defun fzf-melpa-log (format-string &rest args)
  (let ((text (concat (apply #'format format-string args) "\n")))
    (write-region text nil (concat fzf-melpa-root "live-validation.log") t 'silent)))

(defun fzf-melpa-build-packages ()
  (let ((load-path (cons "/Users/ducnguyen/.emacs.d/melpa/package-build" load-path)))
    (require 'package-build))
  (fzf-melpa-log "Live Emacs PID=%s version=%s platform=%s" (emacs-pid) emacs-version system-configuration)
  (dolist (variant '("source-pr" "main" "stable"))
    (let* ((root (concat fzf-melpa-root variant "/"))
           (package-build-directory "/Users/ducnguyen/.emacs.d/melpa/")
           (package-build-recipes-dir (concat package-build-directory "recipes/"))
           (package-build-working-dir (concat root "working/"))
           (package-build-archive-dir (concat root "packages/"))
           (package-build--inhibit-fetch 'strict)
           (package-build--inhibit-checkout nil)
           (package-build--inhibit-build nil)
           (package-build--inhibit-update nil)
           (package-build-all-publishable nil)
           (package-build-releases (equal variant "stable"))
           (package-build-build-function #'package-build--build-multi-file-package)
           (package-build-snapshot-version-functions '(package-build-timestamp-version))
           (package-build-release-version-functions '(package-build-tag-version))
           (package-build-tar-executable (concat fzf-melpa-root "tools/bin/tar"))
           (package-build-timeout nil)
           (package-build-verbose t))
      (package-build-archive "fzf-native" t)
      (let ((archives (directory-files package-build-archive-dir t "\\.tar\\'")))
        (cl-assert (= (length archives) 1))
        (fzf-melpa-log "Built %s archive=%s bytes=%s" variant (car archives)
                       (file-attribute-size (file-attributes (car archives)))))))
  :built)

(defun fzf-melpa-install (variant)
  (let* ((root (concat fzf-melpa-root variant "/"))
         (package-user-dir (concat root "installed/"))
         (package-directory-list nil)
         (package-alist nil)
         (package-activated-list nil)
         (package-selected-packages nil)
         (package-vc-selected-packages nil)
         (package-load-list '(all))
         (package-native-compile nil)
         (package--initialized t)
         (load-path (copy-sequence load-path))
         (custom-file (concat root "custom.el"))
         (archive (car (directory-files (concat root "packages/") t "\\.tar\\'"))))
    (make-directory package-user-dir t)
    (package-install-file archive)
    (let* ((desc (cadr (assq 'fzf-native package-alist)))
           (dir (package-desc-dir desc)))
      (cl-assert (file-exists-p (expand-file-name "fzf-native.elc" dir)))
      (with-temp-file (concat root "installed-path.txt") (insert dir "\n"))
      (fzf-melpa-log "Installed %s with package-install-file, byte-compiled Lisp at %s" variant dir)
      dir)))

(defun fzf-melpa-process (variant label program &rest arguments)
  "Launch a validation command from the existing Emacs without blocking its UI."
  (let* ((root (concat fzf-melpa-root variant "/"))
         (log (concat root label ".log"))
         (buffer (generate-new-buffer (format " *fzf-melpa-%s-%s*" variant label))))
    (make-process
     :name (format "fzf-melpa-%s-%s" variant label)
     :buffer buffer :noquery t :connection-type 'pipe
     :command (cons program arguments)
     :sentinel
     (lambda (process _event)
       (when (memq (process-status process) '(exit signal))
         (with-current-buffer buffer
           (write-region (point-min) (point-max) log nil 'silent))
         (with-temp-file (concat root label ".exit")
           (insert (number-to-string (process-exit-status process)) "\n"))
         (fzf-melpa-log "%s %s exit=%s log=%s" variant label (process-exit-status process) log))))))

(defun fzf-melpa-live-tests (installed)
  (cl-assert (not (featurep 'fzf-native-module)))
  (let* ((load-path (cons installed load-path))
         (process-environment (copy-sequence process-environment))
         (messages-start (with-current-buffer "*Messages*" (copy-marker (point-max))))
         (module (expand-file-name "source-built/fzf-native-module.so" installed)))
    (load (expand-file-name "fzf-native.el" installed) nil t t)
    (module-load module)
    (fzf-native--verify-initialized-module)
    (setq fzf-native-loaded t)
    (setenv "FZF_NATIVE_TEST_MODULE" module)
    (load (concat fzf-melpa-source "fzf-native-test.el") nil t)
    (load (concat fzf-melpa-source "fzf-native-utf8-test.el") nil t)
    (let* ((stats (ert-run-tests-batch "^fzf-native-"))
           (total (ert-stats-total stats))
           (unexpected (ert-stats-completed-unexpected stats))
           (skipped (ert-stats-skipped stats)))
      (with-temp-file (concat fzf-melpa-root "live-ert-results.el")
        (prin1 (list :pid (emacs-pid) :emacs-version emacs-version :module module
                     :total total :unexpected unexpected :skipped skipped
                     :score (fzf-native-score "Hot-Topic" "hp")) (current-buffer)))
      (with-current-buffer "*Messages*"
        (write-region messages-start (point-max) (concat fzf-melpa-root "live-ert-messages.log") nil 'silent))
      (set-marker messages-start nil)
      (fzf-melpa-log "Live ERT total=%s unexpected=%s skipped=%s module=%s" total unexpected skipped module)
      (cl-assert (= unexpected 0))
      (list :total total :unexpected unexpected :skipped skipped :pid (emacs-pid)))))

(provide 'live-validation)
