;;; identity-tests.el --- Session, file, and window identity regressions -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'agent-shell-sidebar)
(require 'agent-shell-anthropic)

(defvar identity-test--buffers nil)

(defmacro identity-test--project (&rest body)
  (declare (indent 0))
  `(let* ((root (file-name-as-directory (make-temp-file "sidebar-identity-" t)))
          (default-directory root)
          (identity-test--buffers nil)
          (agent-shell-sidebar-extra-project-roots (list root))
          (agent-shell-sidebar-refresh-timer nil)
          (agent-shell-sidebar--parse-cache (make-hash-table :test 'equal))
          (projectile-known-projects nil))
     (unwind-protect
         (cl-letf (((symbol-function 'project-known-project-roots) (lambda () nil)))
           (with-temp-buffer
             (agent-shell-sidebar-mode)
             ,@body))
       (dolist (buffer identity-test--buffers)
         (when (buffer-live-p buffer) (kill-buffer buffer)))
       (delete-directory root t))))

(defun identity-test--write (root &optional agent name)
  (let ((file (expand-file-name (format ".agent-shell/transcripts/%s.md" (or name "session")) root)))
    (make-directory (file-name-directory file) t)
    (with-temp-file file
      (when agent (insert (format "**Agent:** %s\n" agent)))
      (insert (format "**Session ID:** session\n**Working Directory:** %s\n---\n## User\nFixture prompt\n" root)))
    file))

(defun identity-test--goto-file (file)
  (agent-shell-sidebar-refresh)
  (goto-char (point-min))
  (while (and (not (eobp))
              (not (equal file (get-text-property (point) 'agent-shell-sidebar-file))))
    (forward-line 1))
  (should-not (eobp)))

(defun identity-test--shell (directory config session-id &optional file)
  "Create a local owner recognized by the installed `agent-shell-buffers'."
  (let ((buffer (generate-new-buffer " *identity fixture shell*")))
    (push buffer identity-test--buffers)
    (with-current-buffer buffer
      (setq-local default-directory directory)
      (setq-local major-mode 'agent-shell-mode)
      (setq-local shell-maker--config 'fixture-config)
      (setq-local agent-shell--transcript-file file)
      (setq-local agent-shell--state (agent-shell--make-state :buffer buffer :agent-config config))
      (map-put! agent-shell--state :resume-session-id session-id))
    (should (memq buffer (agent-shell-buffers)))
    buffer))

(ert-deftest identity-active-session-replaces-pending-identity ()
  (identity-test--project
    (let* ((config '((:mode-line-name . "Claude")))
           (owner (identity-test--shell root config "pending")))
      (should (eq owner (agent-shell-sidebar--live-buffer-for-session "pending" "Claude" root)))
      (with-current-buffer owner
        (map-put! (map-elt agent-shell--state :session) :id ""))
      (should (eq owner (agent-shell-sidebar--live-buffer-for-session "pending" "Claude" root)))
      (with-current-buffer owner
        (map-put! (map-elt agent-shell--state :session) :id "active"))
      (should (eq owner (agent-shell-sidebar--live-buffer-for-session "active" "Claude" root)))
      (should-not (agent-shell-sidebar--live-buffer-for-session "pending" "Claude" root))
      (should-not (agent-shell-sidebar--live-buffer-for-session "" "Claude" root))
      (should-not (agent-shell-sidebar--live-buffer-for-session nil "Claude" root)))))

(ert-deftest identity-substring-alias-reuses-connecting-and-active-shell ()
  (identity-test--project
    (let* ((file (identity-test--write root "Claude Code"))
           (config '((:mode-line-name . "Claude") (:buffer-name . "Claude")))
           (agent-shell-agent-configs (list config))
           (starts 0) shown)
      (identity-test--goto-file file)
      (cl-letf (((symbol-function 'agent-shell-sidebar--start)
                 (lambda (&rest args) (cl-incf starts) (apply #'identity-test--shell args)))
                ((symbol-function 'agent-shell-sidebar--pop-to) (lambda (buffer) (setq shown buffer))))
        (agent-shell-sidebar-visit)
        (let ((first shown))
          (agent-shell-sidebar-visit)
          (should (eq first shown))
          (with-current-buffer first
            (map-put! (map-elt agent-shell--state :session) :id "session"))
          (agent-shell-sidebar-visit)
          (should (eq first shown))))
      (should (= starts 1)))))

(ert-deftest identity-real-config-maker-reuses-across-fresh-resolutions ()
  (identity-test--project
    (let* ((file (identity-test--write root "Claude Code"))
           (agent-shell-agent-configs '(agent-shell-anthropic-make-claude-code-config))
           (first (car (agent-shell--resolved-agent-configs)))
           (second (car (agent-shell--resolved-agent-configs)))
           (starts 0))
      ;; Real installed makers include callback functions, not just names.
      (should-not (eq first second))
      (should (functionp (map-elt first :client-maker)))
      (identity-test--goto-file file)
      (cl-letf (((symbol-function 'agent-shell-sidebar--start)
                 (lambda (&rest args) (cl-incf starts) (apply #'identity-test--shell args)))
                ((symbol-function 'agent-shell-sidebar--pop-to) #'ignore))
        (agent-shell-sidebar-visit)
        (agent-shell-sidebar-visit))
      (message "Installed Claude maker: fresh-alists=t equivalent=%S visits=2 starts=%d"
               (equal first second) starts)
      (should (= starts 1)))))

(ert-deftest identity-ambiguous-alias-obeys-explicit-selection-on-every-visit ()
  (identity-test--project
    (let* ((file (identity-test--write root "Claude"))
           (personal '((:identifier . personal) (:mode-line-name . "Claude Personal")))
           (work '((:identifier . work) (:mode-line-name . "Claude Work")))
           (agent-shell-agent-configs (list personal work))
           (agent-shell-preferred-agent-config nil)
           (agent-shell-show-config-icons nil)
           (choice "Claude Work")
           (prompts 0) (starts 0) shown)
      (identity-test--goto-file file)
      (should-not (agent-shell-sidebar--config-for-agent-name "Claude"))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _) (cl-incf prompts) choice))
                ((symbol-function 'agent-shell-sidebar--start)
                 (lambda (&rest args) (cl-incf starts) (apply #'identity-test--shell args)))
                ((symbol-function 'agent-shell-sidebar--pop-to) (lambda (buffer) (setq shown buffer))))
        (agent-shell-sidebar-visit)
        (let ((first shown))
          (should (equal work (map-elt (buffer-local-value 'agent-shell--state first) :agent-config)))
          (agent-shell-sidebar-visit)
          (should (eq first shown))
          (setq choice "Claude Personal")
          (agent-shell-sidebar-visit)
          (should-not (eq first shown))
          (should (equal personal (map-elt (buffer-local-value 'agent-shell--state shown) :agent-config)))))
      (should (= prompts 3))
      (should (= starts 2)))))

(ert-deftest identity-same-names-do-not-cross-config-directory-or-session ()
  (identity-test--project
    (let* ((file (identity-test--write root "Claude"))
           (config '((:identifier . claude) (:mode-line-name . "Claude") (:profile . work)))
           (other-config '((:identifier . claude) (:mode-line-name . "Claude") (:profile . personal)))
           (other-directory (expand-file-name "other/" root))
           (agent-shell-agent-configs (list config))
           (starts 0) shown)
      (make-directory other-directory)
      (identity-test--shell root other-config "session")
      (identity-test--shell other-directory config "session")
      (identity-test--shell root config "other-session")
      (identity-test--goto-file file)
      (cl-letf (((symbol-function 'agent-shell-sidebar--start)
                 (lambda (&rest args) (cl-incf starts) (apply #'identity-test--shell args)))
                ((symbol-function 'agent-shell-sidebar--pop-to) (lambda (buffer) (setq shown buffer))))
        (agent-shell-sidebar-visit)
        (let ((first shown))
          (agent-shell-sidebar-visit)
          (should (eq first shown))
          (should (equal root (buffer-local-value 'default-directory shown)))
          (should (equal config (map-elt (buffer-local-value 'agent-shell--state shown) :agent-config)))))
      (should (= starts 1)))))

(ert-deftest identity-removed-config-retains-exact-live-session-access ()
  (identity-test--project
    (let* ((file (identity-test--write root "Claude"))
           (config '((:mode-line-name . "Claude")))
           (agent-shell-agent-configs '(((:mode-line-name . "Other")))))
      (let ((owner (identity-test--shell root config "session")) shown)
        (identity-test--goto-file file)
        (cl-letf (((symbol-function 'agent-shell-select-config)
                   (lambda (&rest _) (ert-fail "Prompted for an existing removed configuration")))
                  ((symbol-function 'agent-shell-sidebar--start)
                   (lambda (&rest _) (ert-fail "Started a duplicate removed configuration")))
                  ((symbol-function 'agent-shell-sidebar--pop-to) (lambda (buffer) (setq shown buffer))))
          (agent-shell-sidebar-visit))
        (should (eq owner shown))))))

(ert-deftest identity-unconfigured-exact-name-still-refuses-multiple-configs ()
  (identity-test--project
    (identity-test--shell root '((:mode-line-name . "Claude") (:profile . work)) "session")
    (identity-test--shell root '((:mode-line-name . "Claude") (:profile . personal)) "session")
    (should-not (agent-shell-sidebar--live-buffer-for-session "session" "Claude" root))))

(ert-deftest identity-missing-agent-uses-selected-config-before-reuse ()
  (identity-test--project
    (let* ((file (identity-test--write root))
           (config '((:identifier . preferred) (:mode-line-name . "Preferred")))
           (agent-shell-agent-configs (list config))
           (agent-shell-preferred-agent-config config)
           (wrong (identity-test--shell root '((:mode-line-name . "Other")) "session"))
           (starts 0) shown)
      (identity-test--goto-file file)
      (cl-letf (((symbol-function 'agent-shell-sidebar--start)
                 (lambda (&rest args) (cl-incf starts) (apply #'identity-test--shell args)))
                ((symbol-function 'agent-shell-sidebar--pop-to) (lambda (buffer) (setq shown buffer))))
        (agent-shell-sidebar-visit)
        (should-not (eq wrong shown))
        (agent-shell-sidebar-visit))
      (should (= starts 1)))))

(ert-deftest identity-deletion-protects-directory-alias-in-both-directions ()
  (identity-test--project
    (let* ((real (expand-file-name "real/" root))
           (alias (expand-file-name "alias/" root))
           (file (identity-test--write real "Claude"))
           (alias-file (expand-file-name ".agent-shell/transcripts/session.md" alias))
           (delete-by-moving-to-trash nil))
      (make-symbolic-link (directory-file-name real) (directory-file-name alias))
      (dolist (paths (list (cons file alias-file) (cons alias-file file)))
        (let ((owner (identity-test--shell real nil nil (car paths))))
          (puthash (cdr paths) 'delete agent-shell-sidebar--marks)
          (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
            (agent-shell-sidebar-execute))
          (should (file-exists-p file))
          (should (eq 'delete (gethash (cdr paths) agent-shell-sidebar--marks)))
          (clrhash agent-shell-sidebar--marks)
          (kill-buffer owner))))))

(ert-deftest identity-deletion-protects-hard-links-and-removes-distinct-copy ()
  (identity-test--project
    (let* ((file (identity-test--write root "Claude"))
           (link (expand-file-name "hard-link.md" root))
           (copy (expand-file-name "copy.md" root))
           (delete-by-moving-to-trash nil))
      (add-name-to-file file link)
      (copy-file file copy)
      (identity-test--shell root nil nil file)
      (should (file-equal-p file link))
      (should-not (file-equal-p file copy))
      (dolist (target (list link copy)) (puthash target 'delete agent-shell-sidebar--marks))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (agent-shell-sidebar-execute))
      (should (file-exists-p file))
      (should (file-exists-p link))
      (should (eq 'delete (gethash link agent-shell-sidebar--marks)))
      (should-not (file-exists-p copy))
      (should-not (gethash copy agent-shell-sidebar--marks)))))

(ert-deftest identity-deletion-ignores-absent-owner-paths ()
  (identity-test--project
    (let ((file (identity-test--write root "Claude"))
          (delete-by-moving-to-trash nil))
      (dolist (path (list nil "" (expand-file-name "missing.md" root)))
        (identity-test--shell root nil nil path))
      (puthash file 'delete agent-shell-sidebar--marks)
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
        (agent-shell-sidebar-execute))
      (should-not (file-exists-p file))
      (should-not (gethash file agent-shell-sidebar--marks)))))

(ert-deftest identity-deletion-retains-mark-when-ownership-stat-fails ()
  (identity-test--project
    (let ((file (identity-test--write root "Claude"))
          (owned (identity-test--write root "Claude" "owned"))
          (delete-by-moving-to-trash nil))
      (identity-test--shell root nil nil owned)
      (puthash file 'delete agent-shell-sidebar--marks)
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                ((symbol-function 'file-equal-p) (lambda (&rest _) (signal 'file-error '("Fixture stat failure")))))
        (agent-shell-sidebar-execute))
      (should (file-exists-p file))
      (should (eq 'delete (gethash file agent-shell-sidebar--marks))))))

(ert-deftest identity-toggle-preserves-ordinary-view-and-removes-only-side-window ()
  (save-window-excursion
    (delete-other-windows)
    (identity-test--project
      (let ((ordinary (selected-window))
            (buffer (current-buffer))
            (agent-shell-sidebar-name (buffer-name))
            (agent-shell-sidebar-pop-to-sidebar-on-toggle-open nil))
        (set-window-buffer ordinary buffer)
        (should-not (agent-shell-sidebar-showing-sidebar-p))
        ;; q/hide in an ordinary view must not delete its window.
        (agent-shell-sidebar-hide-sidebar)
        (should (window-live-p ordinary))
        (agent-shell-sidebar-toggle-sidebar)
        (let ((side (agent-shell-sidebar--sidebar-buffer)))
          (should (window-live-p side))
          (should (window-parameter side 'window-side))
          (should-not (eq ordinary side))
          (should (eq buffer (window-buffer ordinary)))
          (agent-shell-sidebar-toggle-sidebar)
          (should-not (window-live-p side)))
        (should (window-live-p ordinary))
        (should (= 1 (length (window-list))))))))

;;; identity-tests.el ends here
