;;; scheduling-tests.el --- Scheduler and rendering regressions -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'timer)

(defmacro scheduling--fixture (count &rest body)
  (declare (indent 1))
  `(let* ((root (file-name-as-directory (make-temp-file "sidebar-scheduling-" t)))
          (default-directory root)
          (agent-shell-sidebar-extra-project-roots (list root))
          (agent-shell-sidebar-refresh-timer nil)
          (agent-shell-sidebar--parse-cache (make-hash-table :test 'equal))
          (agent-shell-sidebar-parse-chunk-size 30)
          (projectile-known-projects nil))
     (unwind-protect
         (cl-letf (((symbol-function 'project-known-project-roots) (lambda () nil))
                   ((symbol-function 'agent-shell-buffers) (lambda () nil)))
           (dotimes (i ,count)
             (let ((file (expand-file-name (format ".agent-shell/transcripts/%05d.md" i) root)))
               (make-directory (file-name-directory file) t)
               (with-temp-file file
                 (insert (format "**Agent:** %s\n**Session ID:** %d\n---\n## User\n\nPrompt %05d\n"
                                 (if (zerop (% i 2)) "Alpha" "Beta") i i)))
               (set-file-times file (seconds-to-time 1000000))))
           (with-temp-buffer
             (agent-shell-sidebar-mode)
             (agent-shell-sidebar-refresh)
             ,@body))
       (delete-directory root t))))

(defun scheduling--drain ()
  "Drain the real owned timer, including work after header parsing ends."
  (let ((ticks 0))
    (while (and (timerp agent-shell-sidebar--parse-timer) (< ticks 2000))
      (timer-event-handler agent-shell-sidebar--parse-timer)
      (cl-incf ticks))
    (should-not agent-shell-sidebar--parse-timer)
    (should-not agent-shell-sidebar--parse-queue)
    (should-not agent-shell-sidebar--render-iterator)
    (should-not agent-shell-sidebar--render-dirty)
    (should-not agent-shell-sidebar--render-error)
    ticks))

(defun scheduling--goto (file)
  (goto-char (point-min))
  (let ((match (text-property-search-forward 'agent-shell-sidebar-file file #'equal)))
    (should match)
    (goto-char (prop-match-beginning match))))

(ert-deftest scheduling-idle-reset-rearms-both-timers-from-another-buffer ()
  (scheduling--fixture 2
    (let ((idle 300)
          (owner (current-buffer))
          (agent-shell-sidebar-refresh-timer 30)
          (agent-shell-sidebar-parse-chunk-size 1))
      (cl-letf (((symbol-function 'current-idle-time)
                 (lambda () (and idle (seconds-to-time idle)))))
        (agent-shell-sidebar--schedule-refresh)
        (timer-event-handler agent-shell-sidebar--parse-timer)
        (should (= 300.1 (float-time (timer--time agent-shell-sidebar--parse-timer))))
        (should (= 330 (float-time (timer--time agent-shell-sidebar--refresh-timer-object))))
        (let ((stale agent-shell-sidebar--parse-timer))
          (setq idle nil)
          (with-temp-buffer (run-hooks 'post-command-hook))
          (should (= 0.1 (float-time (timer--time agent-shell-sidebar--parse-timer))))
          (should (= 30 (float-time (timer--time agent-shell-sidebar--refresh-timer-object))))
          (let ((pending agent-shell-sidebar--pending-count))
            (timer-event-handler stale)
            (should (= pending agent-shell-sidebar--pending-count))))
        (setq idle 30)
        (timer-event-handler agent-shell-sidebar--refresh-timer-object)
        (should (= 60 (float-time (timer--time agent-shell-sidebar--refresh-timer-object))))
        (with-current-buffer owner (scheduling--drain))))))

(ert-deftest scheduling-disabled-refresh-skips-a-pending-callback ()
  (scheduling--fixture 0
    (save-window-excursion
      (set-window-buffer (selected-window) (current-buffer))
      (let ((agent-shell-sidebar-refresh-timer 30))
        (agent-shell-sidebar--schedule-refresh)
        (setq agent-shell-sidebar-refresh-timer nil)
        (cl-letf (((symbol-function 'agent-shell-sidebar--collect)
                   (lambda () (ert-fail "Disabled refresh performed discovery"))))
          (timer-event-handler agent-shell-sidebar--refresh-timer-object))
        (should-not agent-shell-sidebar--refresh-timer-object)))))

(ert-deftest scheduling-transient-standard-read-hook-retries-the-same-head ()
  (scheduling--fixture 2
    (let ((head (car agent-shell-sidebar--parse-queue))
          (calls 0)
          (agent-shell-sidebar-parse-chunk-size 1))
      (let ((after-insert-file-functions
             (list (lambda (_) (cl-incf calls) (error "Transient read hook")))))
        (timer-event-handler agent-shell-sidebar--parse-timer))
      (should (= calls 1))
      (should (equal head (car agent-shell-sidebar--parse-queue)))
      (should (memq agent-shell-sidebar--parse-timer timer-idle-list))
      (scheduling--drain)
      (should (plist-get (agent-shell-sidebar--cached-header head) :session-id))
      (should (string-search "Prompt 00001" (buffer-string))))))

(ert-deftest scheduling-persistent-hook-failure-is-bounded-and-visible ()
  (scheduling--fixture 2
    (let ((calls 0))
      (let ((after-insert-file-functions
             (list (lambda (_) (cl-incf calls) (error "Persistent read hook")))))
        (scheduling--drain))
      (should (= calls 4))
      (should (string-search "[unreadable transcript]" (buffer-string)))
      (dolist (file (cdar agent-shell-sidebar--groups))
        (should (equal "Persistent read hook"
                       (plist-get (agent-shell-sidebar--cached-header file) :error)))))))

(ert-deftest scheduling-quit-retains-work-and-rearms ()
  (scheduling--fixture 2
    (let ((head (car agent-shell-sidebar--parse-queue)))
      (cl-letf (((symbol-function 'agent-shell-sidebar--ensure-parsed)
                 (lambda (_) (signal 'quit nil))))
        (condition-case nil
            (agent-shell-sidebar--parse-tick)
          (quit nil)))
      (should (equal head (car agent-shell-sidebar--parse-queue)))
      (should (memq agent-shell-sidebar--parse-timer timer-idle-list))
      (scheduling--drain))))

(ert-deftest scheduling-rendering-is-progressive-bounded-and-coherent ()
  (scheduling--fixture 600
    (let ((render (symbol-function 'agent-shell-sidebar--render-transcript-row))
          (publish (symbol-function 'agent-shell-sidebar--publish-render))
          (reads (symbol-function 'agent-shell-sidebar--parse-header-from-file))
          (rows 0) (headers 0) (publications 0) progressive)
      (cl-letf (((symbol-function 'agent-shell-sidebar--render-transcript-row)
                 (lambda (&rest args) (cl-incf rows) (apply render args)))
                ((symbol-function 'agent-shell-sidebar--parse-header-from-file)
                 (lambda (file) (cl-incf headers) (funcall reads file)))
                ((symbol-function 'agent-shell-sidebar--publish-render)
                 (lambda ()
                   (funcall publish)
                   (cl-incf publications)
                   (when (and agent-shell-sidebar--parse-queue
                              (string-search "Prompt 00000" (buffer-string)))
                     (setq progressive t))
                   ;; Every shown transcript must agree with its agent header.
                   (save-excursion
                     (goto-char (point-min))
                     (let (agent)
                       (while (not (eobp))
                         (when-let* ((key (get-text-property (point) 'agent-shell-sidebar-agent)))
                           (setq agent (cdr key)))
                         (when (get-text-property (point) 'agent-shell-sidebar-file)
                           (let ((help (get-text-property (point) 'help-echo)))
                             (when (string-search "\nAgent:" help)
                               (should (string-search (concat "\nAgent: " (or agent "?")) help)))))
                         (forward-line 1)))))))
        (let ((ticks 0))
          (while (and (timerp agent-shell-sidebar--parse-timer) (< ticks 200))
            (let ((before-rows rows) (before-headers headers))
              (timer-event-handler agent-shell-sidebar--parse-timer)
              (should (<= (- rows before-rows) 300))
              (should (<= (- headers before-headers) 30)))
            (cl-incf ticks)))
        (should-not agent-shell-sidebar--parse-timer)
        (should progressive)
        (should (> publications 1))
        (should (= headers 600))
        (should (<= rows (* 600 6)))
        (should (string-search "Prompt 00599" (buffer-string)))))))

(ert-deftest scheduling-input-and-mode-change-stop-staged-work ()
  (scheduling--fixture 600
    (timer-event-handler agent-shell-sidebar--parse-timer)
    (should agent-shell-sidebar--render-iterator)
    (let ((stage agent-shell-sidebar--render-buffer)
          (queue agent-shell-sidebar--parse-queue))
      (let ((size (buffer-size stage)))
        (cl-letf (((symbol-function 'input-pending-p) (lambda () t)))
          (timer-event-handler agent-shell-sidebar--parse-timer))
        (should (= size (buffer-size stage)))
        (should (eq queue agent-shell-sidebar--parse-queue)))
      (let ((timer agent-shell-sidebar--parse-timer))
        (fundamental-mode)
        (should-not (buffer-live-p stage))
        (timer-event-handler timer)
        (should-not agent-shell-sidebar--parse-timer)))))

(ert-deftest scheduling-user-redraw-invalidates-stale-filter-and-fold-snapshots ()
  (scheduling--fixture 600
    (timer-event-handler agent-shell-sidebar--parse-timer)
    (let ((stage agent-shell-sidebar--render-buffer))
      (agent-shell-sidebar-set-filter "Alpha")
      (should-not (buffer-live-p stage)))
    (goto-char (point-min))
    (agent-shell-sidebar-toggle-project)
    (scheduling--drain)
    (should-not (text-property-not-all (point-min) (point-max) 'agent-shell-sidebar-file nil))
    (should (gethash root agent-shell-sidebar--collapsed))
    (goto-char (point-min))
    (agent-shell-sidebar-toggle-project)
    (should (string-search "Alpha (300)" (buffer-string)))
    (should-not (string-search "Beta" (buffer-string)))
    (should (string-search "Prompt 00598" (buffer-string)))))

(ert-deftest scheduling-publish-preserves-independent-window-views-and-marks ()
  (scheduling--fixture 600
    (save-window-excursion
      (let* ((one (selected-window))
             (two (split-window one nil 'right))
             (file-a (nth 40 (cdar agent-shell-sidebar--groups)))
             (file-b (nth 70 (cdar agent-shell-sidebar--groups)))
             (file-c (nth 80 (cdar agent-shell-sidebar--groups))))
        (set-window-buffer one (current-buffer))
        (set-window-buffer two (current-buffer))
        (scheduling--goto file-a)
        (set-window-start one (point) t)
        (scheduling--goto file-b)
        (set-window-start two (point) t)
        (scheduling--goto file-c)
        (set-window-point one (point))
        (puthash file-c 'delete agent-shell-sidebar--marks)
        (set-window-point two (point))
        (scheduling--drain)
        (should (equal file-a (get-text-property (window-start one) 'agent-shell-sidebar-file)))
        (should (equal file-b (get-text-property (window-start two) 'agent-shell-sidebar-file)))
        (should (equal file-c (get-text-property (window-point one) 'agent-shell-sidebar-file)))
        (should (equal file-c (get-text-property (window-point two) 'agent-shell-sidebar-file)))
        (should (eq 'delete (gethash file-c agent-shell-sidebar--marks)))))))

(ert-deftest scheduling-snapshot-freezes-header-and-attribute-pair ()
  (scheduling--fixture 600
    (scheduling--drain)
    (let ((file (car (cdar agent-shell-sidebar--groups))))
      (setq agent-shell-sidebar--render-dirty t)
      (agent-shell-sidebar--start-parse-timer)
      (timer-event-handler agent-shell-sidebar--parse-timer)
      (should agent-shell-sidebar--render-iterator)
      ;; This path is already captured, but its row has not been rendered.
      (with-temp-file file
        (insert "**Agent:** Changed\n---\n## User\n\nChanged prompt with a different signature\n"))
      (should (equal "Changed" (plist-get (agent-shell-sidebar--ensure-parsed file) :agent)))
      (scheduling--drain)
      (scheduling--goto file)
      (should (string-search "Prompt 00000" (buffer-substring (line-beginning-position) (line-end-position))))
      (should (string-search "Agent: Alpha" (get-text-property (point) 'help-echo)))
      (agent-shell-sidebar--redraw)
      (scheduling--goto file)
      (should (string-search "Changed prompt" (buffer-substring (line-beginning-position) (line-end-position)))))))

(ert-deftest scheduling-refresh-cancels-snapshot-before-removing-a-file ()
  (scheduling--fixture 600
    (timer-event-handler agent-shell-sidebar--parse-timer)
    (let ((stage agent-shell-sidebar--render-buffer)
          (file (car (last (cdar agent-shell-sidebar--groups)))))
      (delete-file file)
      (agent-shell-sidebar-refresh)
      (should-not (buffer-live-p stage))
      (scheduling--drain)
      (should-not (text-property-any (point-min) (point-max) 'agent-shell-sidebar-file file))
      (should-not (string-search "Prompt 00599" (buffer-string))))))

(ert-deftest scheduling-render-error-stops-and-manual-refresh-recovers ()
  (scheduling--fixture 600
    (cl-letf (((symbol-function 'agent-shell-sidebar--render-transcript-row)
               (lambda (&rest _) (error "Injected render failure"))))
      (let ((ticks 0))
        (while (and agent-shell-sidebar--parse-timer (< ticks 200))
          (timer-event-handler agent-shell-sidebar--parse-timer)
          (cl-incf ticks))))
    (should-not agent-shell-sidebar--parse-timer)
    (should-not agent-shell-sidebar--parse-queue)
    (should-not agent-shell-sidebar--render-iterator)
    (should-not agent-shell-sidebar--render-dirty)
    (should (equal "Injected render failure" agent-shell-sidebar--render-error))
    (should (string-search "redraw failed" header-line-format))
    (agent-shell-sidebar-refresh)
    (should-not agent-shell-sidebar--render-error)
    (should (string-search "Prompt 00599" (buffer-string)))))

(ert-deftest scheduling-quit-discards-a-partially-written-staging-row ()
  (scheduling--fixture 600
    (let ((render (symbol-function 'agent-shell-sidebar--render-transcript-row))
          interrupted)
      (cl-letf (((symbol-function 'agent-shell-sidebar--render-transcript-row)
                 (lambda (&rest args)
                   (unless interrupted
                     (setq interrupted t)
                     (insert "half a row")
                     (signal 'quit nil))
                   (apply render args))))
        (condition-case nil
            (dotimes (_ 10) (agent-shell-sidebar--parse-tick))
          (quit nil)))
      (should interrupted)
      (should-not agent-shell-sidebar--render-iterator)
      (should-not agent-shell-sidebar--render-buffer)
      (should agent-shell-sidebar--render-dirty)
      (should (timerp agent-shell-sidebar--parse-timer))
      (scheduling--drain)
      (should-not (string-search "half a row" (buffer-string)))
      (should (string-search "Prompt 00599" (buffer-string))))))
