;;; scheduling-scale.el --- Measure complete dispatched callback work -*- lexical-binding: t; -*-
(require 'json)
(load (expand-file-name "scheduling-tests.el" (file-name-directory load-file-name)) nil t)

(defun scheduling-scale--percentile (samples p)
  (nth (max 0 (1- (ceiling (* p (length samples))))) (sort (copy-sequence samples) #'<)))

(let ((count (string-to-number (or (getenv "SCHEDULING_FILES") "300"))))
  (scheduling--fixture count
    ;; The fixture's first refresh is outside instrumentation. Recreate cold state.
    (clrhash agent-shell-sidebar--parse-cache)
    (let* ((render (symbol-function 'agent-shell-sidebar--render-transcript-row))
          (publish-function (if (fboundp 'agent-shell-sidebar--publish-render)
                                'agent-shell-sidebar--publish-render
                              'agent-shell-sidebar--redraw))
          (publish (symbol-function publish-function))
          (parse (symbol-function 'agent-shell-sidebar--parse-header-from-file))
          (collect (symbol-function 'agent-shell-sidebar--collect))
          (rows 0) (headers 0) (collections 0) (publications 0)
          (progressive 0) (publish-ms 0.0) (max-publish-ms 0.0)
          (initial-ms 0.0) (max-tick-rows 0) (max-tick-reads 0)
          (gc-before gcs-done) (gc-time-before gc-elapsed) ticks)
      (garbage-collect)
      (cl-letf (((symbol-function 'agent-shell-sidebar--render-transcript-row)
                 (lambda (&rest args) (cl-incf rows) (apply render args)))
                ((symbol-function 'agent-shell-sidebar--parse-header-from-file)
                 (lambda (file) (cl-incf headers) (funcall parse file)))
                ((symbol-function 'agent-shell-sidebar--collect)
                 (lambda () (cl-incf collections) (funcall collect)))
                ((symbol-function publish-function)
                 (lambda ()
                   (let ((start (float-time)))
                     (funcall publish)
                     (let ((ms (* 1000 (- (float-time) start))))
                       (cl-incf publish-ms ms)
                       (setq max-publish-ms (max max-publish-ms ms))))
                   (cl-incf publications)
                   (when (and agent-shell-sidebar--parse-queue
                              (string-search "Prompt 00000" (buffer-string)))
                     (cl-incf progressive)))))
        (let ((start (float-time)))
          (agent-shell-sidebar-refresh)
          (setq initial-ms (* 1000 (- (float-time) start))))
        (when (getenv "SCHEDULING_WINDOW")
          (set-window-buffer (selected-window) (current-buffer))
          (goto-char (point-min))
          (forward-line (/ count 2))
          (set-window-start (selected-window) (point) t)
          (forward-line 4))
        (let ((callbacks 0))
          (while (and (timerp agent-shell-sidebar--parse-timer) (< callbacks 2000))
            (let ((start (float-time)) (before-rows rows) (before-reads headers))
              (timer-event-handler agent-shell-sidebar--parse-timer)
              (push (* 1000 (- (float-time) start)) ticks)
              (setq max-tick-rows (max max-tick-rows (- rows before-rows))
                    max-tick-reads (max max-tick-reads (- headers before-reads))))
            (cl-incf callbacks)))
        (cl-assert (null agent-shell-sidebar--parse-queue))
        (cl-assert (null agent-shell-sidebar--parse-timer))
        (cl-assert (not (bound-and-true-p agent-shell-sidebar--render-iterator)))
        (cl-assert (not (bound-and-true-p agent-shell-sidebar--render-dirty)))
        (cl-assert (not (bound-and-true-p agent-shell-sidebar--render-error)))
        (cl-assert (> progressive 0))
        (cl-assert (string-search (format "Prompt %05d" (1- count)) (buffer-string)))
        (princ
         (concat
          "SCHEDULING "
          (json-encode
           `((files . ,count) (emacs . ,emacs-version)
             (publication-function . ,publish-function)
             (displayed-window . ,(and (getenv "SCHEDULING_WINDOW") t))
             (compiled . ,(byte-code-function-p (symbol-function 'agent-shell-sidebar--parse-tick)))
             (initial-refresh-ms . ,initial-ms) (callbacks . ,(length ticks))
             (callback-median-ms . ,(scheduling-scale--percentile ticks 0.5))
             (callback-p95-ms . ,(scheduling-scale--percentile ticks 0.95))
             (callback-max-ms . ,(apply #'max ticks))
             (total-work-ms . ,(+ initial-ms (apply #'+ ticks)))
             (publish-total-ms . ,publish-ms) (publish-max-ms . ,max-publish-ms)
             (rows . ,rows) (max-callback-rows . ,max-tick-rows)
             (headers . ,headers) (max-callback-headers . ,max-tick-reads)
             (collections . ,collections) (publications . ,publications)
             (progressive-publications . ,progressive)
             (gc-count . ,(- gcs-done gc-before)) (gc-ms . ,(* 1000 (- gc-elapsed gc-time-before)))
             (method . "Real timer-event-handler dispatch until both parsing and staging finish; all callbacks timed including native publication; idle delays and screen redisplay excluded; fresh metadata cache; OS cache not flushed")))
          "\n"))))))
