;;; contrarian-workflow-tests.el --- Context-sensitive command evidence -*- lexical-binding: t; -*-
(load (expand-file-name "../../tests.el" (file-name-directory load-file-name)) nil t)

(ert-deftest review-workflow-new-rejects-native-missing-cwd ()
  (codex-test--fixture
    (let* ((file (codex-test--write agent-sidebar-codex-home nil))
           (agent-shell-sidebar--context-roots (list root)) launched)
      (agent-sidebar-refresh) (merge--drain) (merge--goto file)
      (cl-letf (((symbol-function 'agent-sidebar--require-codex-terminal) #'ignore)
                ((symbol-function 'agent-sidebar--launch-terminal)
                 (lambda (_name _program _args directory) (setq launched directory))))
        (let ((result (condition-case err (agent-sidebar-new-session) (user-error err))))
          (message "MISSING CWD: result=%S launch=%S" result launched)
          (should (eq (car-safe result) 'user-error))
          (should-not launched))))))

(ert-deftest review-workflow-new-rejects-native-error-row ()
  (codex-test--fixture
    (let* ((file (codex-test--write agent-sidebar-codex-home root "invalid-id"))
           (agent-shell-sidebar--context-roots (list root)) launched)
      (agent-sidebar-refresh) (merge--drain) (merge--goto file)
      (should (plist-get (agent-sidebar--cached-meta (gethash file agent-sidebar--entries)) :error))
      (should (string-search "[unreadable transcript]" (buffer-string)))
      (cl-letf (((symbol-function 'agent-sidebar--require-codex-terminal) #'ignore)
                ((symbol-function 'agent-sidebar--launch-terminal)
                 (lambda (_name _program _args directory) (setq launched directory))))
        (let ((result (condition-case err (agent-sidebar-new-session) (user-error err))))
          (message "ERROR ROW: result=%S launch=%S" result launched)
          (should (eq (car-safe result) 'user-error))
          (should-not launched))))))

(ert-deftest review-workflow-new-revalidates-changed-native-directory ()
  (codex-test--fixture
    (let* ((file (codex-test--write agent-sidebar-codex-home root))
           (new-root (expand-file-name "changed-existing-repository/" temporary)) launched)
      (make-directory new-root t)
      (agent-sidebar-refresh) (merge--drain) (merge--goto file)
      ;; Refresh is intentionally absent: activation must revalidate cached metadata.
      (codex-test--write agent-sidebar-codex-home new-root)
      (cl-letf (((symbol-function 'agent-sidebar--require-codex-terminal) #'ignore)
                ((symbol-function 'agent-sidebar--launch-terminal)
                 (lambda (_name _program _args directory) (setq launched directory))))
        (agent-sidebar-new-session))
      (message "CHANGED CWD: expected=%S launch=%S" new-root launched)
      (should (equal launched new-root)))))

(ert-deftest review-workflow-repo-only-group-keeps-unique-codex-provider ()
  (codex-test--fixture
    (codex-test--write agent-sidebar-codex-home root)
    (agent-sidebar-refresh) (merge--drain)
    (agent-sidebar-set-grouping '(repo model))
    (goto-char (point-min))
    (should (equal (get-text-property (point) 'agent-sidebar-group) (list (cons 'repo root))))
    (let (calls)
      (cl-letf (((symbol-function 'agent-sidebar--require-codex-terminal) #'ignore)
                ((symbol-function 'agent-sidebar--launch-terminal)
                 (lambda (name _program _args directory) (push (list 'terminal name directory) calls)))
                ((symbol-function 'agent-shell-sidebar--select-config)
                 (lambda (name) (list :name name)))
                ((symbol-function 'agent-shell-sidebar--start)
                 (lambda (directory config &rest _) (push (list 'agent-shell directory config) calls) buffer))
                ((symbol-function 'agent-shell-sidebar--pop-to) #'ignore))
        (agent-sidebar-new-session))
      (message "REPO-ONLY CODEX GROUP: calls=%S" calls)
      (should (equal calls (list (list 'terminal "*codex-new*" root)))))))

(ert-deftest review-workflow-ret-and-a-reject-native-missing-cwd-control ()
  (codex-test--fixture
    (let ((file (codex-test--write agent-sidebar-codex-home nil)))
      (agent-sidebar-refresh) (merge--drain) (merge--goto file)
      (cl-letf (((symbol-function 'agent-sidebar--require-codex-terminal) #'ignore)
                ((symbol-function 'agent-sidebar--launch-terminal)
                 (lambda (&rest _) (ert-fail "RET started a missing-CWD session")))
                ((symbol-function 'agent-sidebar--codex-start-agent-shell)
                 (lambda (&rest _) (ert-fail "A started a missing-CWD session"))))
        (should-error (agent-sidebar-visit) :type 'user-error)
        (should-error (agent-sidebar-visit-in-agent-shell) :type 'user-error)))))
