;;; torvalds-tests.el --- Independent terminal identity probes -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'agent-sidebar)

(defmacro torvalds--term-fixture (&rest body)
  (declare (indent 0))
  `(let* ((temporary (make-temp-file "sidebar-torvalds-" t))
          (directory (file-name-as-directory (expand-file-name "repo" temporary)))
          (home (file-name-as-directory (expand-file-name "codex" temporary)))
          (agent-sidebar-terminal-function nil)
          (agent-sidebar-refresh-timer nil)
          (before (buffer-list))
          (processes nil))
     (make-directory directory t)
     (make-directory home t)
     (unwind-protect
         (save-window-excursion ,@body)
       (dolist (process processes)
         (when (process-live-p process) (delete-process process)))
       (dolist (buffer (buffer-list))
         (unless (memq buffer before)
           (when-let* ((process (get-buffer-process buffer)))
             (set-process-query-on-exit-flag process nil)
             (when (process-live-p process) (delete-process process)))
           (when (buffer-live-p buffer)
             (with-current-buffer buffer (setq-local kill-buffer-query-functions nil))
             (kill-buffer buffer))))
       (delete-directory temporary t))))

(ert-deftest torvalds-codex-home-trailing-slash-reuses-process ()
  "Equivalent local home names must identify the same resumed session."
  (torvalds--term-fixture
    (let* ((agent-sidebar-codex-cli-command "/bin/cat")
           (id "12345678-1234-7123-8123-123456789abc")
           (meta (list :session-id id :cwd directory))
           (entry (list :provider 'codex-cli :id (expand-file-name "rollout.jsonl" home)
                        :extras (list :codex-home home)))
           (starts 0))
      (cl-letf (((symbol-function 'agent-sidebar--ensure-parsed) (lambda (_) meta))
                ((symbol-function 'agent-shell-sidebar--pop-to) #'ignore)
                ((symbol-function 'ghostel-exec)
                 (lambda (buffer program args)
                   (should (equal program "/bin/cat"))
                   (should (equal args (list "resume" id)))
                   (cl-incf starts)
                   (let ((process (make-process :name "torvalds-ghostel" :buffer buffer
                                                :command '("/bin/cat") :noquery t)))
                     (push process processes) process))))
        (agent-sidebar--codex-visit entry)
        (agent-sidebar--codex-visit entry)
        (should (= starts 1))
        (setf (plist-get (plist-get entry :extras) :codex-home) (directory-file-name home))
        (agent-sidebar--codex-visit entry)
        (message "TRAILING-SLASH: starts=%s, live-children=%s, both homes equal by file-equal-p=%S"
                 starts (length (seq-filter #'process-live-p processes))
                 (file-equal-p home (directory-file-name home)))
        (should (= starts 1))))))

(ert-deftest torvalds-term-fallback-distinguishes-resume-id-prefix-collision ()
  "Two different session IDs must never share a term buffer or child."
  (torvalds--term-fixture
    (let* ((first "12345678-1111-7111-8111-111111111111")
           (second "12345678-2222-7222-8222-222222222222")
           (entry1 (list :provider 'claude-cli :id (expand-file-name "first.jsonl" temporary)))
           (entry2 (list :provider 'claude-cli :id (expand-file-name "second.jsonl" temporary)))
           shown first-buffer second-buffer)
      (cl-letf (((symbol-function 'ghostel-exec) nil)
                ((symbol-function 'vterm) nil)
                ((symbol-function 'agent-shell-sidebar--pop-to) (lambda (buffer) (setq shown buffer)))
                ((symbol-function 'agent-sidebar--ensure-parsed)
                 (lambda (entry) (list :session-id (if (eq entry entry1) first second) :cwd directory))))
        (agent-sidebar--visit-terminal entry1 "claude" "/bin/sh" '("-c" "exec sleep 30" "fixture"))
        (setq first-buffer shown)
        (push (get-buffer-process first-buffer) processes)
        (set-process-query-on-exit-flag (car processes) nil)
        (should (process-live-p (car processes)))
        (should (equal (cadr (buffer-local-value 'agent-sidebar--terminal-session first-buffer)) first))
        (agent-sidebar--visit-terminal entry2 "claude" "/bin/sh" '("-c" "exec sleep 30" "fixture"))
        (setq second-buffer shown)
        (push (get-buffer-process second-buffer) processes)
        (message "TERM-COLLISION: same-buffer=%S, same-process=%S, child-command=%S, recorded-session=%S"
                 (eq first-buffer second-buffer) (eq (car processes) (cadr processes))
                 (process-command (car processes))
                 (buffer-local-value 'agent-sidebar--terminal-session second-buffer))
        (should-not (eq first-buffer second-buffer))
        (should-not (eq (car processes) (cadr processes)))))))

(ert-deftest torvalds-term-new-session-really-starts-new-process ()
  "The public new-session command creates a fresh process on each call."
  (torvalds--term-fixture
    (let ((agent-sidebar-claude-cli-command "/bin/cat") shown first-buffer)
      (with-temp-buffer
        (insert (propertize "fixture row\n" 'agent-sidebar-entry
                            (list :provider 'claude-cli :repo directory)))
        (goto-char (point-min))
        (cl-letf (((symbol-function 'ghostel-exec) nil)
                  ((symbol-function 'vterm) nil)
                  ((symbol-function 'agent-shell-sidebar--pop-to) (lambda (buffer) (setq shown buffer))))
          (agent-sidebar-new-session)
          (setq first-buffer shown)
          (push (get-buffer-process shown) processes)
          (set-process-query-on-exit-flag (car processes) nil)
          (should (process-live-p (car processes)))
          (agent-sidebar-new-session)
          (push (get-buffer-process shown) processes)
          (message "TERM-NEW: same-buffer=%S, same-process=%S"
                   (eq first-buffer shown) (eq (car processes) (cadr processes)))
          (should-not (eq first-buffer shown)))))))
