;;; contrarian-workflow.el --- Fresh user workflow review -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'timer)
(setq native-comp-enable-subr-trampolines nil)
(defconst cw2-source (symbol-file 'agent-shell-sidebar-visit 'defun))
(message "CW2 reviewed source: %s" cw2-source)

(defmacro cw2-fixture (count &rest body)
  (declare (indent 1))
  `(let* ((root (file-name-as-directory (make-temp-file "sidebar-cw2-" t)))
          (default-directory root)
          (agent-shell-sidebar-extra-project-roots (list root))
          (agent-shell-sidebar-refresh-timer nil)
          (agent-shell-sidebar-parse-chunk-size 20)
          (projectile-known-projects nil)
          (files nil))
     (unwind-protect
         (cl-letf (((symbol-function 'project-known-project-roots) (lambda () nil))
                   ((symbol-function 'agent-shell-buffers) (lambda () nil)))
           (dotimes (i ,count)
             (let ((file (expand-file-name (format ".agent-shell/transcripts/%04d.md" i) root)))
               (make-directory (file-name-directory file) t)
               (with-temp-file file
                 (insert (format "**Agent:** Fixture\n**Session ID:** session-%d\n**Working Directory:** %s\n---\n## User\nPrompt %04d\n" i root i)))
               (push file files)))
           (setq files (nreverse files))
           (with-temp-buffer
             (agent-shell-sidebar-mode)
             (agent-shell-sidebar-refresh)
             ,@body))
       (dolist (file files)
         (when-let* ((buffer (find-buffer-visiting file))) (kill-buffer buffer)))
       (delete-directory root t))))

(defun cw2-goto (file)
  (goto-char (point-min))
  (let ((position (text-property-any (point-min) (point-max) 'agent-shell-sidebar-file file)))
    ;; `text-property-any' compares strings by identity, while refresh may
    ;; discover a new path string. Use the displayed row's value comparison.
    (unless position
      (while (and (not (eobp))
                  (not (equal file (get-text-property (point) 'agent-shell-sidebar-file))))
        (forward-line 1))
      (unless (eobp) (setq position (point))))
    (should position)
    (goto-char position)))

(defun cw2-row-mark (file)
  (save-excursion
    (cw2-goto file)
    (char-after (+ (line-beginning-position) 4))))

(defun cw2-drain ()
  (let ((ticks 0))
    (while (and (timerp agent-shell-sidebar--parse-timer) (< ticks 1000))
      (timer-event-handler agent-shell-sidebar--parse-timer)
      (cl-incf ticks))
    (should-not agent-shell-sidebar--parse-timer)
    (should-not agent-shell-sidebar--parse-queue)
    (should-not agent-shell-sidebar--render-iterator)
    (should-not agent-shell-sidebar--render-error)
    (should-not agent-shell-sidebar--render-dirty)
    ticks))

(ert-deftest cw2-mark-command-invalidates-staged-metadata-publication ()
  (cw2-fixture 420
    (timer-event-handler agent-shell-sidebar--parse-timer)
    (should agent-shell-sidebar--render-iterator)
    (let ((staged agent-shell-sidebar--render-buffer)
          (marked (nth 210 files)))
      (cw2-goto marked)
      (agent-shell-sidebar-mark-delete)
      (should-not (buffer-live-p staged))
      (should (eq (gethash marked agent-shell-sidebar--marks) 'delete))
      (should (= (cw2-row-mark marked) ?D))
      (let ((ticks (cw2-drain)))
        (should (= (cw2-row-mark marked) ?D))
        (should (string-search "Prompt 0210" (buffer-string)))
        (cw2-goto marked)
        (agent-shell-sidebar-unmark)
        (should-not (gethash marked agent-shell-sidebar--marks))
        (should (= (cw2-row-mark marked) ?\s))
        (message "CW2 staged mark: pending metadata completed in %d ticks; mark and unmark visible" ticks)))))

(ert-deftest cw2-cancel-deletion-while-metadata-pending-keeps-marks-and-files ()
  (cw2-fixture 3
    (cw2-goto (car files))
    (agent-shell-sidebar-mark-delete)
    (cw2-goto (cadr files))
    (agent-shell-sidebar-mark-delete)
    (should agent-shell-sidebar--parse-queue)
    (dolist (quit-p '(nil t))
      (let ((confirmed nil)
            (real-delete (symbol-function 'delete-file)))
        (cl-letf (((symbol-function 'yes-or-no-p)
                   (lambda (&rest _) (setq confirmed t) (if quit-p (signal 'quit nil) nil)))
                  ((symbol-function 'delete-file)
                   (lambda (file &optional trash)
                     (if (member file files)
                         (ert-fail "Deletion occurred after cancellation")
                       ;; Installing another stub can compile a native
                       ;; trampoline and remove its own scratch file.
                       (funcall real-delete file trash)))))
          (condition-case nil (agent-shell-sidebar-execute) (quit nil)))
        (should confirmed)
        (should (= 2 (hash-table-count agent-shell-sidebar--marks)))
        (should (cl-every #'file-exists-p files))))
    (cw2-drain)
    (should (= (cw2-row-mark (car files)) ?D))
    (should (= (cw2-row-mark (cadr files)) ?D))
    (message "CW2 deletion cancellation: no and quit both retain 2 marks; metadata still completes")))

(ert-deftest cw2-delete-partial-success-retains-failed-visible-mark ()
  (cw2-fixture 2
    (dolist (file files) (cw2-goto file) (agent-shell-sidebar-mark-delete))
    (let ((blocked (cadr files)) (real-delete (symbol-function 'delete-file)) (attempted nil))
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                ((symbol-function 'delete-file)
                 (lambda (file &optional trash)
                   (when (member file files) (push file attempted))
                   (if (equal file blocked) (signal 'file-error '("Fixture deletion denied"))
                     (funcall real-delete file trash)))))
        (agent-shell-sidebar-execute))
      (should (= 2 (length attempted)))
      (should (equal (sort (copy-sequence attempted) #'string<)
                     (sort (copy-sequence files) #'string<)))
      (should-not (file-exists-p (car files)))
      (should (file-exists-p blocked))
      (should (= 1 (hash-table-count agent-shell-sidebar--marks)))
      (should (eq 'delete (gethash blocked agent-shell-sidebar--marks)))
      (cw2-drain)
      (should (= (cw2-row-mark blocked) ?D))
      (should (= 1 (length (cdar agent-shell-sidebar--groups))))
      (message "CW2 partial deletion: actual file deleted; failed file retained with visible D"))))

(defun cw2-ambiguous-selection (cancel)
  (cw2-fixture 1
    (let* ((a '((:identifier . "fixture-a") (:mode-line-name . "Fixture")))
           (b '((:identifier . "fixture-b") (:mode-line-name . "Fixture")))
           (agent-shell-agent-configs (list a b))
           (live-a (generate-new-buffer " *cw2 live a*"))
           (live-b (generate-new-buffer " *cw2 live b*"))
           (selected 0) popped)
      (unwind-protect
          (progn
            (dolist (pair (list (cons live-a a) (cons live-b b)))
              (with-current-buffer (car pair)
                (setq-local default-directory root)
                (setq-local agent-shell--state
                            (list (cons :agent-config (cdr pair))
                                  '(:session (:id . "session-0"))))))
            (cw2-goto (car files))
            (let ((initial (point)))
              (cl-letf (((symbol-function 'agent-shell-buffers) (lambda () (list live-a live-b)))
                        ((symbol-function 'agent-shell-select-config)
                         (lambda (&rest _) (cl-incf selected)
                           (if cancel (signal 'quit nil) b)))
                        ((symbol-function 'agent-shell-sidebar--start)
                         (lambda (&rest _) (ert-fail "Started instead of respecting explicit selection")))
                        ((symbol-function 'agent-shell-sidebar--pop-to)
                         (lambda (buffer) (setq popped buffer))))
                (condition-case nil (agent-shell-sidebar-visit) (quit nil)))
              (should (= selected 1))
              (should (= initial (point)))
              (should (if cancel (null popped) (eq popped live-b))))
            (message "CW2 ambiguous selection: cancel=%S prompted=%d target=%S"
                     cancel selected (and popped (buffer-name popped))))
        (kill-buffer live-a) (kill-buffer live-b)))))

(ert-deftest cw2-ambiguous-live-session-selection-cancellation ()
  (cw2-ambiguous-selection t))
(ert-deftest cw2-ambiguous-live-session-explicit-choice-reuses-selected-config ()
  (cw2-ambiguous-selection nil))

(ert-deftest cw2-real-view-command-keeps-side-window-and-selects-ordinary-window ()
  (save-window-excursion
    (delete-other-windows)
    (cw2-fixture 1
      (let* ((sidebar (current-buffer))
             (ordinary (selected-window))
             (agent-shell-sidebar-width 20)
             (agent-shell-sidebar-resize-on-open nil)
             (side (display-buffer-in-side-window sidebar '((side . left) (window-width . 20)))))
        (set-window-dedicated-p side t)
        (select-window side)
        (cw2-goto (car files))
        (agent-shell-sidebar-open-transcript)
        (should (eq (selected-window) ordinary))
        (should (eq (window-buffer side) sidebar))
        (should (window-dedicated-p side))
        (should (bound-and-true-p view-mode))
        (should (equal (buffer-file-name) (car files)))
        (should (string-search "Prompt 0000" (buffer-string)))
        (message "CW2 regular view: ordinary selected, dedicated sidebar retained, View mode active")))))

(ert-deftest cw2-hide-side-window-preserves-two-ordinary-sidebar-views ()
  (save-window-excursion
    (delete-other-windows)
    (cw2-fixture 1
      (let* ((sidebar (current-buffer))
             (first (selected-window))
             (second (split-window-below))
             (agent-shell-sidebar-name (buffer-name))
             (agent-shell-sidebar-width 20)
             (agent-shell-sidebar-resize-on-open nil))
        (set-window-buffer first sidebar)
        (set-window-buffer second sidebar)
        (cl-letf (((symbol-function 'project-current) (lambda (&rest _) nil)))
          (agent-shell-sidebar-show-sidebar))
        (let ((side (agent-shell-sidebar-showing-sidebar-p)))
          (should (window-live-p side))
          (should (window-parameter side 'window-side))
          (agent-shell-sidebar-hide-sidebar)
          (should-not (window-live-p side))
          (should (window-live-p first))
          (should (window-live-p second))
          (should (eq (window-buffer first) sidebar))
          (should (eq (window-buffer second) sidebar))
          (should-not (agent-shell-sidebar-showing-sidebar-p))
          (message "CW2 hide: side window removed; both ordinary sidebar views retained"))))))

(ert-deftest cw2-disable-pending-refresh-keeps-manual-refresh-available ()
  (cw2-fixture 1
    (let ((agent-shell-sidebar-refresh-timer 30) (scans 0)
          (collect (symbol-function 'agent-shell-sidebar--collect)))
      (agent-shell-sidebar--schedule-refresh)
      (let ((pending agent-shell-sidebar--refresh-timer-object))
        (setq agent-shell-sidebar-refresh-timer nil)
        (cl-letf (((symbol-function 'get-buffer-window) (lambda (&rest _) (selected-window)))
                  ((symbol-function 'agent-shell-sidebar--collect)
                   (lambda () (cl-incf scans) (funcall collect))))
          (timer-event-handler pending)
          (should (= scans 0))
          (should-not agent-shell-sidebar--refresh-timer-object)
          (agent-shell-sidebar-refresh)
          (should (= scans 1))
          (cw2-drain))
        (message "CW2 refresh: disabled pending scan skipped; explicit refresh performs one scan")))))

(add-hook 'kill-emacs-hook
          (lambda () (message "CW2 final source: %s" (symbol-file 'agent-shell-sidebar-visit 'defun))))
