;;; kingsbury-probe.el --- Round 2 independent schedules -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'timer)

(defmacro kingsbury2--fixture (&rest body)
  (declare (indent 0))
  `(let* ((root (file-name-as-directory (make-temp-file "sidebar-kingsbury2-" t)))
          (default-directory root)
          (agent-shell-sidebar-extra-project-roots (list root))
          (agent-shell-sidebar-refresh-timer nil)
          (agent-shell-sidebar-parse-chunk-size 30)
          (projectile-known-projects nil))
     (unwind-protect
         (cl-letf (((symbol-function 'project-known-project-roots) (lambda () nil))
                   ((symbol-function 'agent-shell-buffers) (lambda () nil)))
           (dotimes (i 600)
             (let ((file (expand-file-name (format ".agent-shell/transcripts/%04d.md" i) root)))
               (make-directory (file-name-directory file) t)
               (with-temp-file file
                 (insert (format "**Agent:** %s\n---\n## User\n\nMessage %04d\n"
                                 (if (zerop (% i 3)) "Alpha" "Beta") i)))
               (set-file-times file (seconds-to-time 1000000))))
           (let ((owner (generate-new-buffer " *Kingsbury owner*")))
             (unwind-protect
                 (with-current-buffer owner
                   (agent-shell-sidebar-mode)
                   (agent-shell-sidebar-refresh)
                   ,@body)
               (when (buffer-live-p owner) (kill-buffer owner)))))
       (delete-directory root t))))

(defun kingsbury2--dispatch ()
  (should (memq agent-shell-sidebar--parse-timer timer-idle-list))
  (timer-event-handler agent-shell-sidebar--parse-timer))

(defun kingsbury2--finish ()
  (let ((callbacks 0))
    (while (and agent-shell-sidebar--parse-timer (< callbacks 200))
      (kingsbury2--dispatch)
      (cl-incf callbacks))
    (should-not agent-shell-sidebar--parse-timer)
    (should-not agent-shell-sidebar--parse-queue)
    (should-not agent-shell-sidebar--render-iterator)
    (should-not agent-shell-sidebar--render-dirty)))

(defun kingsbury2--find (property value)
  (goto-char (point-min))
  (while (and (not (eobp)) (not (equal value (get-text-property (point) property))))
    (forward-line 1))
  (should-not (eobp)))

(ert-deftest kingsbury2-mark-unmark-filter-agent-fold-schedule ()
  (kingsbury2--fixture
    (kingsbury2--dispatch)
    (let ((first-stage agent-shell-sidebar--render-buffer)
          (target (expand-file-name ".agent-shell/transcripts/0300.md" root)))
      (kingsbury2--find 'agent-shell-sidebar-file target)
      (agent-shell-sidebar-mark-delete)
      (should-not (buffer-live-p first-stage))
      (kingsbury2--dispatch)
      (kingsbury2--find 'agent-shell-sidebar-file target)
      (agent-shell-sidebar-unmark)
      (kingsbury2--find 'agent-shell-sidebar-file target)
      (agent-shell-sidebar-mark-delete)
      (agent-shell-sidebar-set-filter "Alpha")
      (kingsbury2--dispatch)
      (let ((stage agent-shell-sidebar--render-buffer))
        (kingsbury2--find 'agent-shell-sidebar-agent (cons root "Alpha"))
        (agent-shell-sidebar-toggle-project)
        (should-not (buffer-live-p stage)))
      (kingsbury2--finish)
      (should (gethash (cons root "Alpha") agent-shell-sidebar--collapsed))
      (should (string-search "Alpha (200)" (buffer-string)))
      (should-not (text-property-not-all (point-min) (point-max) 'agent-shell-sidebar-file nil))
      (kingsbury2--find 'agent-shell-sidebar-agent (cons root "Alpha"))
      (agent-shell-sidebar-toggle-project)
      (let ((rows 0))
        (goto-char (point-min))
        (while (not (eobp))
          (when-let* ((file (get-text-property (point) 'agent-shell-sidebar-file)))
            (cl-incf rows)
            (should (zerop (% (string-to-number (file-name-base file)) 3))))
          (forward-line 1))
        (should (= rows 200)))
      (kingsbury2--find 'agent-shell-sidebar-file target)
      (should (looking-at-p "    D "))
      (should (eq 'delete (gethash target agent-shell-sidebar--marks)))
      (message "Mark/unmark/filter/agent-fold schedule: exactly 200 Alpha rows, target mark retained."))))

(ert-deftest kingsbury2-killing-one-owner-does-not-cancel-the-other ()
  (kingsbury2--fixture
    (let ((first (current-buffer))
          (second (generate-new-buffer " *Kingsbury second owner*")))
      (unwind-protect
          (progn
            (kingsbury2--dispatch)
            (let ((stage agent-shell-sidebar--render-buffer)
                  (cancelled agent-shell-sidebar--parse-timer))
              (with-current-buffer second
                (agent-shell-sidebar-mode)
                (agent-shell-sidebar-refresh)
                (kingsbury2--dispatch))
              (kill-buffer first)
              (should-not (buffer-live-p stage))
              (timer-event-handler cancelled)
              (with-temp-buffer (run-hooks 'post-command-hook))
              (with-current-buffer second
                (kingsbury2--finish)
                (should (string-search "Message 0599" (buffer-string)))
                (should (memq second agent-shell-sidebar--timer-buffers))
                (should-not (memq first agent-shell-sidebar--timer-buffers))))
            (message "Owner cancellation: other sidebar completed after the first owner and its stage were killed."))
        (when (buffer-live-p second) (kill-buffer second))))))

(ert-deftest kingsbury2-deletion-while-staged-cannot-resurrect-a-row ()
  (kingsbury2--fixture
    (kingsbury2--dispatch)
    (let ((target (expand-file-name ".agent-shell/transcripts/0300.md" root))
          (delete-by-moving-to-trash nil))
      (kingsbury2--find 'agent-shell-sidebar-file target)
      (agent-shell-sidebar-mark-delete)
      (kingsbury2--dispatch)
      (let ((stage agent-shell-sidebar--render-buffer)
            (old-timer agent-shell-sidebar--parse-timer))
        (cl-letf (((symbol-function 'yes-or-no-p) (lambda (_) t)))
          (agent-shell-sidebar-execute))
        (should-not (buffer-live-p stage))
        (should-not (file-exists-p target))
        (timer-event-handler old-timer))
      (kingsbury2--finish)
      (should-not (gethash target agent-shell-sidebar--marks))
      (should-not (gethash target agent-shell-sidebar--parse-cache))
      (should-not (string-search "Message 0300" (buffer-string)))
      (message "Deletion schedule: old timer cannot restore the deleted transcript or its mark."))))

(ert-deftest kingsbury2-external-stage-kill-produces-bounded-explicit-error ()
  (kingsbury2--fixture
    (kingsbury2--dispatch)
    (kill-buffer agent-shell-sidebar--render-buffer)
    (kingsbury2--finish)
    (should agent-shell-sidebar--render-error)
    (should (string-search "redraw failed" header-line-format))
    (agent-shell-sidebar-refresh)
    (should-not agent-shell-sidebar--render-error)
    (should (string-search "Message 0599" (buffer-string)))
    (message "Externally killed stage: one explicit renderer error, drained headers, manual refresh recovered.")))
