;;; luu-probe.el --- Full callback and grouping probes -*- lexical-binding: t; -*-
(require 'cl-lib)
(require 'json)
(require 'agent-shell-sidebar)

(defun luu--emit (kind values)
  (princ (concat "LUU " (json-encode (cons (cons 'kind kind) values)) "\n")))

(defun luu--percentile (numbers fraction)
  (nth (max 0 (1- (ceiling (* fraction (length numbers)))))
       (sort (copy-sequence numbers) #'<)))

(defun luu--count-shown ()
  (save-excursion
    (goto-char (point-min))
    (let ((n 0))
      (while (re-search-forward "Prompt [0-9]" nil t) (cl-incf n))
      n)))

(defun luu--workload (count variant)
  (let* ((root (file-name-as-directory (make-temp-file "/private/tmp/sidebar-luu-r2-fixture-" t)))
         (agent-shell-sidebar-extra-project-roots (list root))
         (projectile-known-projects nil)
         (agent-shell-sidebar-refresh-timer nil)
         (agent-shell-sidebar-parse-chunk-size 30)
         (default-directory root))
    (unwind-protect
        (cl-letf (((symbol-function 'project-known-project-roots) (lambda () nil))
                  ((symbol-function 'agent-shell-buffers) (lambda () nil)))
          (dotimes (i count)
            (let ((file (expand-file-name (format ".agent-shell/transcripts/%05d.md" i) root)))
              (make-directory (file-name-directory file) t)
              (with-temp-file file
                (insert (format "**Agent:** %s\n**Started:** 2026-09-08 12:30:00\n**Session ID:** %d\n---\n## User\n\nPrompt %05d %s\n"
                                (if (equal variant "unique-agents") (format "Agent-%05d" i) "Claude")
                                i i (if (equal variant "long-preview") (make-string 7000 ?x) ""))))
              (set-file-times file (seconds-to-time 1000000))))
          (with-temp-buffer
            (agent-shell-sidebar-mode)
            (save-window-excursion
              (set-window-buffer (selected-window) (current-buffer))
              (let ((render (symbol-function 'agent-shell-sidebar--render-transcript-row))
                    (publish (symbol-function 'agent-shell-sidebar--publish-render))
                    (parse (symbol-function 'agent-shell-sidebar--parse-header-from-file))
                    (rows 0) (reads 0) (tick 0) (parse-done-tick nil)
                    (max-rows 0) (max-reads 0) (gc-before nil) (gc-time nil)
                    (max-publish-ms 0.0) (publish-total-ms 0.0) publications samples warm)
                (cl-letf (((symbol-function 'agent-shell-sidebar--render-transcript-row)
                           (lambda (&rest values) (cl-incf rows) (apply render values)))
                          ((symbol-function 'agent-shell-sidebar--parse-header-from-file)
                           (lambda (file) (cl-incf reads) (funcall parse file)))
                          ((symbol-function 'agent-shell-sidebar--publish-render)
                           (lambda ()
                             (let ((start (float-time)))
                               (funcall publish)
                               (let ((duration (* 1000 (- (float-time) start))))
                                 (cl-incf publish-total-ms duration)
                                 (setq max-publish-ms (max max-publish-ms duration))))
                             (push `((tick . ,tick) (pending . ,agent-shell-sidebar--pending-count)
                                     (shown . ,(luu--count-shown)) (buffer-bytes . ,(buffer-size))) publications))))
                  (garbage-collect)
                  (setq gc-before gcs-done gc-time gc-elapsed)
                  (let ((start (float-time)) initial-ms)
                    (agent-shell-sidebar-refresh)
                    (setq initial-ms (* 1000 (- (float-time) start)))
                    (goto-char (point-max))
                    (forward-line -5)
                    (set-window-start (selected-window) (point) t)
                    (while (and (timerp agent-shell-sidebar--parse-timer) (< tick 2000))
                      (cl-incf tick)
                      (let ((start (float-time)) (before-rows rows) (before-reads reads))
                        (timer-event-handler agent-shell-sidebar--parse-timer)
                        (push (* 1000 (- (float-time) start)) samples)
                        (setq max-rows (max max-rows (- rows before-rows))
                              max-reads (max max-reads (- reads before-reads))))
                      (when (and (not parse-done-tick) (not agent-shell-sidebar--parse-queue))
                        (setq parse-done-tick tick)))
                    (cl-assert (null agent-shell-sidebar--parse-timer))
                    (cl-assert (null agent-shell-sidebar--parse-queue))
                    (cl-assert (null agent-shell-sidebar--render-iterator))
                    (cl-assert (null agent-shell-sidebar--render-dirty))
                    (cl-assert (null agent-shell-sidebar--render-error))
                    (cl-assert (= count reads))
                    (cl-assert (= count (luu--count-shown)))
                    (cl-assert (cl-some (lambda (p) (and (> (alist-get 'pending p) 0) (> (alist-get 'shown p) 0))) publications))
                    (luu--emit "full-workload"
                               `((variant . ,variant) (files . ,count) (compiled . t)
                                 (initial-ms . ,initial-ms) (callbacks . ,tick)
                                 (parse-done-tick . ,parse-done-tick)
                                 (render-only-callbacks . ,(- tick parse-done-tick))
                                 (callback-median-ms . ,(luu--percentile samples 0.5))
                                 (callback-p95-ms . ,(luu--percentile samples 0.95))
                                 (callback-max-ms . ,(apply #'max samples))
                                 (total-work-ms . ,(+ initial-ms (apply #'+ samples)))
                                 (publish-total-ms . ,publish-total-ms) (publish-max-ms . ,max-publish-ms)
                                 (rows . ,rows) (max-callback-rows . ,max-rows) (max-callback-reads . ,max-reads)
                                 (gc-count . ,(- gcs-done gc-before)) (gc-ms . ,(* 1000 (- gc-elapsed gc-time)))
                                 (publications . ,(vconcat (nreverse publications)))
                                 (method . "Real timer-event-handler until parsing and staging finish; native publication timed; shown-row scan included in callback time but excluded from publish time; idle delay and redisplay excluded; OS cache not flushed")))
                    (dotimes (_ 3)
                      (let ((warm-start (float-time)) (before-reads reads))
                        (agent-shell-sidebar-refresh)
                        (push (* 1000 (- (float-time) warm-start)) warm)
                        (cl-assert (= reads before-reads))
                        (cl-assert (null agent-shell-sidebar--parse-timer))))
                    (luu--emit "warm" `((variant . ,variant) (files . ,count) (refresh-ms . ,(vconcat (nreverse warm)))))))))))
      (delete-directory root t))))

(defun luu--names ()
  (dolist (count '(300 1200 3000))
    (let* ((roots (cl-loop for i below count collect (format "/private/tmp/parent-%05d/project/" i)))
           (start (float-time))
           (names (agent-shell-sidebar--disambiguated-names roots))
           (elapsed (* 1000 (- (float-time) start))))
      (cl-assert (= count (hash-table-count names)))
      (cl-assert (equal "parent-00000/project" (gethash (car roots) names)))
      (luu--emit "colliding-project-names" `((projects . ,count) (elapsed-ms . ,elapsed))))))

(defun luu--idle-reset ()
  (let ((agent-shell-sidebar-refresh-timer 30) (idle 300))
    (with-temp-buffer
      (agent-shell-sidebar-mode)
      (cl-letf (((symbol-function 'current-idle-time) (lambda () (and idle (seconds-to-time idle)))))
        (agent-shell-sidebar--schedule-refresh)
        (setq agent-shell-sidebar--render-dirty t)
        (agent-shell-sidebar--start-parse-timer)
        (let ((old-parse agent-shell-sidebar--parse-timer)
              (old-refresh agent-shell-sidebar--refresh-timer-object)
              (initial-parse (float-time (timer--time agent-shell-sidebar--parse-timer)))
              (initial-refresh (float-time (timer--time agent-shell-sidebar--refresh-timer-object))))
          (setq idle nil)
          (with-temp-buffer (run-hooks 'post-command-hook))
          (cl-assert (= 0.1 (float-time (timer--time agent-shell-sidebar--parse-timer))))
          (cl-assert (= 30 (float-time (timer--time agent-shell-sidebar--refresh-timer-object))))
          (cl-assert (not (memq old-parse timer-idle-list)))
          (cl-assert (not (memq old-refresh timer-idle-list)))
          (luu--emit "idle-reset" `((old-parse-seconds . ,initial-parse) (old-refresh-seconds . ,initial-refresh)
                                    (new-parse-seconds . ,(float-time (timer--time agent-shell-sidebar--parse-timer)))
                                    (new-refresh-seconds . ,(float-time (timer--time agent-shell-sidebar--refresh-timer-object))))))))))

(pcase (getenv "LUU_CASE")
  ("names" (luu--names))
  ("idle-reset" (luu--idle-reset))
  (variant (luu--workload (string-to-number (or (getenv "LUU_FILES") "3000")) variant)))
