;;; ousterhout-probe.el --- Round 2 ownership probes -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'timer)
(require 'agent-shell-sidebar)

(defvar ousterhout2--fixture nil)

(defun ousterhout2--write (root index)
  "Write a transcript and record independently known metadata."
  (let* ((file (expand-file-name (format ".agent-shell/transcripts/%03d.md" index) root))
         (agent (if (zerop (% index 2)) "Alpha" "Beta"))
         (preview (format "%s topic %03d" agent index)))
    (make-directory (file-name-directory file) t)
    (with-temp-file file
      (insert (format "**Agent:** %s\n**Working Directory:** %s\n**Session ID:** session-%03d\n---\n## User\n%s\n"
                      agent root index preview)))
    (set-file-times file (seconds-to-time 1000000))
    (puthash file (list :root root :agent agent :preview preview) ousterhout2--fixture)
    file))

(defmacro ousterhout2--project (count &rest body)
  "Create two projects with COUNT transcripts each and two sidebar buffers."
  (declare (indent 1))
  `(let* ((directory (file-name-as-directory (make-temp-file "sidebar-ousterhout2-" t)))
          (roots (list (expand-file-name "one/" directory) (expand-file-name "two/" directory)))
          (default-directory directory)
          (ousterhout2--fixture (make-hash-table :test 'equal))
          (agent-shell-sidebar-extra-project-roots roots)
          (agent-shell-sidebar-refresh-timer nil)
          (agent-shell-sidebar-parse-chunk-size 7)
          (projectile-known-projects nil)
          (one (generate-new-buffer " *ousterhout2 one*"))
          (two (generate-new-buffer " *ousterhout2 two*")))
     (unwind-protect
         (cl-letf (((symbol-function 'project-known-project-roots) (lambda () nil))
                   ((symbol-function 'agent-shell-buffers) (lambda () nil))
                   ((symbol-function 'input-pending-p) (lambda () nil)))
           (dolist (root roots)
             (dotimes (index ,count) (ousterhout2--write root index)))
           (dolist (buffer (list one two))
             (with-current-buffer buffer
               (agent-shell-sidebar-mode)
               (agent-shell-sidebar-refresh)))
           ,@body)
       (dolist (buffer (list one two))
         (when (buffer-live-p buffer) (kill-buffer buffer)))
       (delete-directory directory t))))

(defun ousterhout2--tick (buffer)
  "Dispatch BUFFER's owned timer in the batch process."
  (with-current-buffer buffer
    (when (timerp agent-shell-sidebar--parse-timer)
      (timer-event-handler agent-shell-sidebar--parse-timer))))

(defun ousterhout2--drain (buffers)
  "Interleave owned timers until BUFFERS have no deferred work."
  (let ((ticks 0))
    (while (and (< ticks 500)
                (seq-some (lambda (buffer)
                            (timerp (buffer-local-value 'agent-shell-sidebar--parse-timer buffer)))
                          buffers))
      (dolist (buffer buffers) (ousterhout2--tick buffer))
      (cl-incf ticks))
    (dolist (buffer buffers)
      (with-current-buffer buffer
        (should-not agent-shell-sidebar--parse-timer)
        (should-not agent-shell-sidebar--parse-queue)
        (should (= 0 agent-shell-sidebar--pending-count))
        (should-not agent-shell-sidebar--render-iterator)
        (should-not agent-shell-sidebar--render-buffer)
        (should-not agent-shell-sidebar--render-dirty)
        (should-not agent-shell-sidebar--render-error)))
    ticks))

(defun ousterhout2--goto-file (file)
  "Move to FILE's row."
  (goto-char (point-min))
  (let ((match (text-property-search-forward 'agent-shell-sidebar-file file #'equal)))
    (should match)
    (goto-char (prop-match-beginning match))))

(defun ousterhout2--assert-view ()
  "Check final rows against fixture data and compare both rendering paths."
  (let (actual expected current-root current-agent)
    (save-excursion
      (goto-char (point-min))
      (while (not (eobp))
        (when-let* ((root (get-text-property (point) 'agent-shell-sidebar-project)))
          (setq current-root root current-agent nil))
        (when-let* ((key (get-text-property (point) 'agent-shell-sidebar-agent)))
          (should (equal current-root (car key)))
          (setq current-agent (cdr key)))
        (when-let* ((file (get-text-property (point) 'agent-shell-sidebar-file)))
          (let ((known (gethash file ousterhout2--fixture)))
            (should known)
            (should (equal current-root (plist-get known :root)))
            (should (equal current-agent (plist-get known :agent)))
            (should (string-search (plist-get known :preview)
                                   (buffer-substring-no-properties (line-beginning-position) (line-end-position))))
            (should (eq (char-after (+ 4 (line-beginning-position)))
                        (if (eq (gethash file agent-shell-sidebar--marks) 'delete) ?D ?\s)))
            (push file actual)))
        (forward-line 1)))
    (dolist (group agent-shell-sidebar--groups)
      (dolist (file (cdr group))
        (let* ((known (gethash file ousterhout2--fixture))
               (root (plist-get known :root))
               (agent (plist-get known :agent)))
          (when (and (not (gethash root agent-shell-sidebar--collapsed))
                     (not (gethash (cons root agent) agent-shell-sidebar--collapsed))
                     (or (string-empty-p agent-shell-sidebar--filter)
                         (equal agent-shell-sidebar--filter agent)))
            (push file expected)))))
    (should (equal (sort actual #'string<) (sort expected #'string<)))
    (let ((staged (buffer-substring (point-min) (point-max))))
      (agent-shell-sidebar--redraw)
      (should (equal-including-properties staged (buffer-substring (point-min) (point-max)))))
    (length actual)))

(ert-deftest ousterhout2-interleaved-buffers-preserve-final-snapshot-ownership ()
  (ousterhout2--project 180
    (ousterhout2--tick one)
    (ousterhout2--tick two)
    (let ((stage-one (buffer-local-value 'agent-shell-sidebar--render-buffer one))
          (stage-two (buffer-local-value 'agent-shell-sidebar--render-buffer two)))
      (should (buffer-live-p stage-one))
      (should (buffer-live-p stage-two))
      (should-not (eq stage-one stage-two))
      (with-current-buffer one
        (agent-shell-sidebar-set-filter "Alpha")
        (goto-char (point-min))
        (agent-shell-sidebar-toggle-project))
      (should-not (buffer-live-p stage-one))
      (should (buffer-live-p stage-two)))
    (with-current-buffer two
      (agent-shell-sidebar-set-filter "Beta")
      (ousterhout2--goto-file (expand-file-name ".agent-shell/transcripts/001.md" (cadr roots)))
      (agent-shell-sidebar-mark-delete))
    (dotimes (_ 6)
      (ousterhout2--tick two)
      (ousterhout2--tick one))
    ;; Refresh one owner while the other keeps its earlier discovery snapshot.
    (dolist (root roots) (ousterhout2--write root 180))
    (with-current-buffer one (agent-shell-sidebar-refresh))
    (let ((ticks (ousterhout2--drain (list two one))))
      (with-current-buffer one
        (should (= 362 (hash-table-count agent-shell-sidebar--file-info)))
        (should (= 91 (ousterhout2--assert-view))))
      (with-current-buffer two
        (should (= 360 (hash-table-count agent-shell-sidebar--file-info)))
        (should (= 180 (ousterhout2--assert-view))))
      (should-not (eq (buffer-local-value 'agent-shell-sidebar--parse-cache one)
                      (buffer-local-value 'agent-shell-sidebar--parse-cache two)))
      (message "R2 ownership control: isolated caches, independent folds/filter/mark, 91 + 180 final rows, %d remaining ticks" ticks))))

(ert-deftest ousterhout2-killing-one-owner-leaves-other-staging-work-live ()
  (ousterhout2--project 180
    (ousterhout2--tick one)
    (ousterhout2--tick two)
    (let ((stage-one (buffer-local-value 'agent-shell-sidebar--render-buffer one))
          (stage-two (buffer-local-value 'agent-shell-sidebar--render-buffer two))
          (timer-one (buffer-local-value 'agent-shell-sidebar--parse-timer one))
          (timer-two (buffer-local-value 'agent-shell-sidebar--parse-timer two)))
      (kill-buffer one)
      (should-not (buffer-live-p stage-one))
      (should-not (memq timer-one timer-idle-list))
      (should-not (memq one agent-shell-sidebar--timer-buffers))
      (should (buffer-live-p stage-two))
      (should (memq timer-two timer-idle-list))
      (should (memq two agent-shell-sidebar--timer-buffers))
      (ousterhout2--drain (list two))
      (with-current-buffer two (should (= 360 (ousterhout2--assert-view))))
      (message "R2 lifecycle control: killing one owner cancels only its staging buffer/timer; surviving view has 360 rows"))))

(ert-deftest ousterhout2-reinitialization-releases-old-generator-and-local-cache ()
  (ousterhout2--project 180
    (ousterhout2--tick one)
    (with-current-buffer one
      (let ((cache agent-shell-sidebar--parse-cache)
            (stage agent-shell-sidebar--render-buffer)
            (timer agent-shell-sidebar--parse-timer))
        (should agent-shell-sidebar--render-iterator)
        (agent-shell-sidebar-mode)
        (should-not (buffer-live-p stage))
        (should-not (memq timer timer-idle-list))
        (should-not (eq cache agent-shell-sidebar--parse-cache))
        (should (= 0 (hash-table-count agent-shell-sidebar--parse-cache)))
        (should (= 1 (seq-count (lambda (buffer) (eq buffer one)) agent-shell-sidebar--timer-buffers)))
        (agent-shell-sidebar-refresh)))
    (ousterhout2--drain (list one two))
    (dolist (buffer (list one two))
      (with-current-buffer buffer (should (= 360 (ousterhout2--assert-view)))))
    (message "R2 mode reset control: old cache/staging/timer released, one registry entry, both reconstructed views have 360 rows")))

(ert-deftest ousterhout2-transient-read-failure-does-not-cross-owner-queues ()
  (ousterhout2--project 20
    (let ((head (car (buffer-local-value 'agent-shell-sidebar--parse-queue one)))
          (calls 0))
      (let ((after-insert-file-functions
             (list (lambda (_) (cl-incf calls) (error "One-owner transient fixture error")))))
        (ousterhout2--tick one))
      (should (= calls 1))
      (with-current-buffer one
        (should (equal head (car agent-shell-sidebar--parse-queue)))
        (should (= 40 agent-shell-sidebar--pending-count))
        (agent-shell-sidebar-set-filter "Alpha"))
      (ousterhout2--tick two)
      (with-current-buffer two
        (should (= 33 agent-shell-sidebar--pending-count))
        (should-not agent-shell-sidebar--parse-retry-file))
      (ousterhout2--drain (list one two))
      (with-current-buffer one (should (= 20 (ousterhout2--assert-view))))
      (with-current-buffer two (should (= 40 (ousterhout2--assert-view))))
      (message "R2 retry control: failed owner retained its head; other owner advanced independently; final rows 20 + 40"))))

;;; ousterhout-probe.el ends here
