;;; torvalds-probe.el --- Round 2 API controls -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'agent-shell-sidebar)
(require 'agent-shell-mock-agent)

(ert-deftest torvalds2-real-startup-rejects-missing-command-without-shell-leak ()
  (let* ((root (file-name-as-directory (make-temp-file "sidebar-torvalds2-start-" t)))
         (directory (expand-file-name "sub/" root))
         (agent-shell-mock-agent-acp-command (list (expand-file-name "absent-agent-executable" root)))
         (config (agent-shell-mock-agent-make-agent-config))
         (agent-shell-show-config-icons nil)
         (agent-shell-header-style 'text)
         (enable-local-variables nil)
         (enable-local-eval nil)
         (before (agent-shell-buffers))
         (original-directory default-directory)
         (original-cwd-function agent-shell-cwd-function))
    (unwind-protect
        (progn
          (make-directory directory)
          (let ((err (should-error (agent-shell-sidebar--start directory config "session"))))
            (should (string-search "absent-agent-executable" (error-message-string err))))
          (should (equal before (agent-shell-buffers)))
          (should (equal original-directory default-directory))
          (should (eq original-cwd-function agent-shell-cwd-function))
          (message "STARTUP CONTROL: real missing-command failure leaves no shell and restores caller directory/CWD function"))
      (dolist (buffer (seq-difference (agent-shell-buffers) before))
        (with-current-buffer buffer
          (setq-local kill-buffer-query-functions nil)
          (kill-buffer buffer)))
      (delete-directory root t))))

(ert-deftest torvalds2-fallback-display-preserves-dedicated-document-and-sidebar ()
  (save-window-excursion
    (delete-other-windows)
    (let ((document (generate-new-buffer " *torvalds2 document*"))
          (sidebar (generate-new-buffer " *torvalds2 sidebar*"))
          (target (generate-new-buffer " *torvalds2 target*"))
          (split-height-threshold 0)
          (split-width-threshold nil)
          (agent-shell-sidebar-refresh-timer nil))
      (unwind-protect
          (let ((document-window (selected-window)))
            (set-window-buffer document-window document)
            (with-current-buffer sidebar (agent-shell-sidebar-mode))
            (let ((side-window (display-buffer-in-side-window sidebar '((side . left) (window-width . 20)))))
              (set-window-dedicated-p document-window t)
              (set-window-dedicated-p side-window t)
              (select-window side-window)
              (agent-shell-sidebar--pop-to target)
              (should (eq document (window-buffer document-window)))
              (should (eq sidebar (window-buffer side-window)))
              (should (eq target (window-buffer (selected-window))))
              (should-not (window-parameter (selected-window) 'window-side))
              (should-not (window-dedicated-p (selected-window)))
              (message "WINDOW CONTROL: fallback created an ordinary target window and preserved both dedicated windows")))
        (dolist (window (window-list)) (set-window-dedicated-p window nil))
        (kill-buffer target)
        (kill-buffer sidebar)
        (kill-buffer document)))))

;;; torvalds-probe.el ends here
