;;; tests.el --- Codex sidebar checks -*- lexical-binding: t; -*-
(load (expand-file-name "../agent-sidebar-merge/tests.el" (file-name-directory load-file-name)) nil t)
(require 'agent-shell-openai)

(defconst codex-test--id "12345678-1234-7123-8123-123456789abc")
(defconst codex-test--other-id "23456789-1234-7123-8123-123456789abc")
(defconst codex-test--fixture
  (expand-file-name "acp-fixture.py" (file-name-directory load-file-name)))

(defun codex-test--write (home cwd &optional id records)
  (let* ((id (or id codex-test--id))
         (file (expand-file-name (format "sessions/2026/09/08/rollout-2026-09-08T12-00-00-%s.jsonl" id) home)))
    (make-directory (file-name-directory file) t)
    (with-temp-file file
      (dolist (record
               (or records
                   `(((type . "session_meta")
                      (payload . ((id . ,id) (session_id . "different-runtime-id") (cwd . ,cwd)
                                  (timestamp . "2026-09-08T19:00:00Z")
                                  (base_instructions . ((text . "Internal instructions"))))))
                     ((type . "response_item")
                      (payload . ((type . "message") (role . "user")
                                  (content . [((type . "input_text") (text . "# AGENTS.md instructions\nignore"))
                                              ((type . "input_text") (text . "<environment_context>ignore</environment_context>"))
                                              ((type . "input_text") (text . "Native Codex prompt\nnext line"))]))))
                     ((type . "turn_context") (payload . ((model . "codex-fixture-model")))))))
        (insert (json-encode record) "\n")))
    file))

(defmacro codex-test--fixture (&rest body)
  (declare (indent 0))
  `(merge--fixture
     (let ((agent-sidebar-codex-home (expand-file-name "codex/" temporary))
           (agent-sidebar-enabled-providers '(agent-shell claude-cli codex-cli)))
       (make-directory agent-sidebar-codex-home t)
       ,@body)))

(ert-deftest codex-discovery-metadata-and-existing-providers ()
  (codex-test--fixture
    (let ((native (codex-test--write agent-sidebar-codex-home root))
          (shell (merge--markdown root "codex" codex-test--id "Codex")))
      (merge--json-file root store "claude")
      (agent-sidebar-refresh) (merge--drain)
      (should (= (length (merge--rows)) 3))
      (should (string-search "Codex CLI (1)" (buffer-string)))
      (should (string-search "codex-fixture-model (1)" (buffer-string)))
      (should (string-search "Native Codex prompt" (buffer-string)))
      (should-not (string-search "Internal instructions" (buffer-string)))
      (let ((meta (agent-sidebar--cached-meta (gethash native agent-sidebar--entries))))
        (should (equal (plist-get meta :session-id) codex-test--id))
        (should (equal (plist-get meta :cwd) root)))
      (should (equal (plist-get (agent-sidebar--cached-meta (gethash shell agent-sidebar--entries)) :agent) "Codex"))
      (agent-sidebar-set-filter "codex-fixture-model")
      (should (equal (merge--rows) (list native))))))

(ert-deftest codex-discovery-ignores-archives-symlinks-pipes-and-unrelated-folders ()
  (codex-test--fixture
    (let* ((file (codex-test--write agent-sidebar-codex-home root))
           (day (file-name-directory file))
           (pipe (expand-file-name "rollout-pipe.jsonl" day)))
      (make-symbolic-link file (expand-file-name "rollout-alias.jsonl" day))
      (should (= 0 (call-process "mkfifo" nil nil nil pipe)))
      (make-symbolic-link (expand-file-name "sessions/2026" agent-sidebar-codex-home)
                         (expand-file-name "sessions/2025" agent-sidebar-codex-home))
      (make-directory (expand-file-name "archived_sessions" agent-sidebar-codex-home))
      (copy-file file (expand-file-name "archived_sessions/rollout-archive.jsonl" agent-sidebar-codex-home))
      (make-directory (expand-file-name "sessions/unrelated" agent-sidebar-codex-home))
      (copy-file file (expand-file-name "sessions/unrelated/rollout-no.jsonl" agent-sidebar-codex-home))
      (should (equal (mapcar (lambda (entry) (plist-get entry :id)) (agent-sidebar--codex-list)) (list file))))))

(ert-deftest codex-bounded-records-and-malformed-session-id ()
  (codex-test--fixture
    (let ((file (codex-test--write agent-sidebar-codex-home root)))
      (with-temp-buffer
        (insert (json-encode `((type . "response_item") (payload . ((padding . ,(make-string 300000 ?x)))))) "\n"
                (json-encode '((type . "event_msg") (payload . ((type . "user_message") (message . "outside prefix"))))) "\n")
        (write-region (point-min) (point-max) file t 'silent))
      (let ((meta (agent-sidebar--codex-parse (list :id file))))
        (should (equal (plist-get meta :preview) "Native Codex prompt"))
        (should (equal (plist-get meta :session-id) codex-test--id)))
      (with-temp-file file
        (insert (json-encode '((type . "session_meta") (payload . ((id . "--last") (cwd . "/")))))))
      (should (plist-get (agent-sidebar--codex-parse (list :id file)) :error)))))

(ert-deftest codex-fork-keeps-first-session-meta-and-first-user-preview ()
  (codex-test--fixture
    (let ((file (codex-test--write agent-sidebar-codex-home root)))
      (with-temp-buffer
        (insert (json-encode `((type . "session_meta") (payload . ((id . ,codex-test--other-id) (cwd . "/wrong"))))) "\n"
                (json-encode '((type . "event_msg") (payload . ((type . "user_message") (message . "Actual user event\nnext"))))) "\n"
                "not json\n{\"type\":\"turn_context\",\"payload\":42}\n")
        (write-region (point-min) (point-max) file t 'silent))
      (let ((meta (agent-sidebar--codex-parse (list :id file))))
        (should (equal (plist-get meta :session-id) codex-test--id))
        (should (equal (plist-get meta :cwd) root))
        (should (equal (plist-get meta :preview) "Native Codex prompt"))))))

(ert-deftest codex-cli-ghostel-resume-argv-home-and-reuse ()
  (codex-test--fixture
    (let ((file (codex-test--write agent-sidebar-codex-home root))
          (agent-sidebar-codex-cli-command "/bin/cat")
          (original-home (getenv "CODEX_HOME")) (starts 0) terminals)
      (unwind-protect
          (cl-letf (((symbol-function 'ghostel-exec)
                     (lambda (target program args)
                       (cl-incf starts) (push target terminals)
                       (should (equal program "/bin/cat"))
                       (should (equal args (list "resume" codex-test--id)))
                       (should (equal default-directory root))
                       (should (equal (getenv "CODEX_HOME") agent-sidebar-codex-home))
                       (make-process :name "codex-ghostel-fixture" :buffer target :command '("/bin/cat") :noquery t)))
                    ((symbol-function 'agent-shell-sidebar--pop-to) #'ignore))
            (agent-sidebar-refresh) (merge--drain)
            (merge--goto file) (end-of-line)
            (agent-sidebar-visit) (agent-sidebar-visit)
            (should (= starts 1))
            (should (agent-sidebar--owned-file-p file))
            (should (equal (getenv "CODEX_HOME") original-home))
            ;; Reuse is scoped to a Codex home as well as the id and cwd.
            (let ((agent-sidebar-codex-home (expand-file-name "other-home" temporary)))
              (make-directory agent-sidebar-codex-home)
              (let ((other (codex-test--write agent-sidebar-codex-home root)))
                (agent-sidebar-refresh) (merge--drain) (merge--goto other)
                (agent-sidebar-visit)))
            (should (= starts 2)))
        (dolist (terminal terminals)
          (when-let* ((process (get-buffer-process terminal))) (delete-process process))
          (kill-buffer terminal))))))

(ert-deftest codex-new-cli-and-prefix-agent-shell-select-codex ()
  (codex-test--fixture
    (let ((file (codex-test--write agent-sidebar-codex-home root)) calls)
      (agent-sidebar-refresh) (merge--drain) (merge--goto file)
      (cl-letf (((symbol-function 'agent-sidebar--require-codex-terminal) #'ignore)
                ((symbol-function 'agent-sidebar--launch-terminal)
                 (lambda (name command args dir) (push (list name command args dir) calls)))
                ((symbol-function 'agent-sidebar--codex-start-agent-shell)
                 (lambda (dir &optional id) (push (list 'agent-shell dir id) calls) buffer))
                ((symbol-function 'agent-shell-sidebar--pop-to) #'ignore))
        (agent-sidebar-new-session)
        (should (equal (car calls) (list "*codex-new*" agent-sidebar-codex-cli-command nil root)))
        (agent-sidebar-new-session t)
        (should (equal (car calls) (list 'agent-shell root nil)))))))

(ert-deftest codex-markdown-agent-shell-uses-codex-config ()
  (codex-test--fixture
    (let ((file (merge--markdown root "codex" codex-test--id "Codex"))
          (config (agent-shell-openai-make-codex-config)) captured)
      (agent-sidebar-refresh) (merge--drain) (merge--goto file)
      (let ((agent-shell-agent-configs (list config)))
        (cl-letf (((symbol-function 'agent-shell-sidebar--start)
                   (lambda (dir chosen id &optional strategy)
                     (setq captured (list dir chosen id strategy)) buffer))
                  ((symbol-function 'agent-shell-sidebar--pop-to) #'ignore))
          (agent-sidebar-visit)))
      (should (equal captured (list root config codex-test--id nil))))))

(ert-deftest codex-native-agent-shell-rejects-missing-cwd-before-start ()
  (codex-test--fixture
    (let ((file (codex-test--write agent-sidebar-codex-home (expand-file-name "missing" root))))
      (agent-sidebar-refresh) (merge--drain) (merge--goto file)
      (cl-letf (((symbol-function 'agent-shell-sidebar--start) (lambda (&rest _) (ert-fail "Started without cwd"))))
        (should-error (agent-sidebar-visit-in-agent-shell) :type 'user-error)))))

(ert-deftest codex-native-real-agent-shell-client-load-new-reuse-and-ownership ()
  (codex-test--fixture
    (let* ((file (codex-test--write agent-sidebar-codex-home root))
           (log (expand-file-name "acp.jsonl" temporary))
           (agent-shell-openai-codex-acp-command (list (executable-find "python3") codex-test--fixture log))
           (config (agent-shell-openai-make-codex-config))
           (agent-shell-agent-configs (list config))
           (agent-shell-openai-authentication (agent-shell-openai-make-authentication :login t))
           (agent-shell-prefer-viewport-interaction nil)
           (agent-shell-show-welcome-message nil) (agent-shell-show-config-icons nil)
           (agent-shell-header-style 'text) (agent-shell-inhibit-system-sleep nil)
           (agent-shell-session-restore-verbosity 'full)
           (enable-local-variables nil) (enable-local-eval nil)
           (delete-by-moving-to-trash nil) shells shown)
      (unwind-protect
          (cl-letf (((symbol-function 'agent-shell-sidebar--pop-to) (lambda (target) (setq shown target))))
            (agent-sidebar-refresh) (merge--drain) (merge--goto file)
            (agent-sidebar-visit-in-agent-shell)
            (push shown shells)
            (let ((deadline (+ (float-time) 8)))
              (while (and (< (float-time) deadline)
                          (not (equal codex-test--id (map-nested-elt (buffer-local-value 'agent-shell--state shown) '(:session :id)))))
                (accept-process-output nil 0.02)))
            (should (equal codex-test--id (map-nested-elt (buffer-local-value 'agent-shell--state shown) '(:session :id))))
            (cl-letf (((symbol-function 'agent-shell-buffers) (lambda () shells))
                      ((symbol-function 'agent-shell-sidebar--start) (lambda (&rest _) (ert-fail "Duplicate Codex shell"))))
              (agent-sidebar-visit-in-agent-shell)
              (should (eq shown (car shells))))
            (should (agent-sidebar--owned-file-p file))
            (merge--goto file) (agent-sidebar-mark-delete)
            (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
              (agent-sidebar-execute))
            (should (file-exists-p file))
            (should (eq (gethash file agent-sidebar--marks) 'delete))
            (merge--goto file) (agent-sidebar-new-session t)
            (push shown shells)
            (let ((deadline (+ (float-time) 8)))
              (while (and (< (float-time) deadline)
                          (not (equal "fixture-new-session" (map-nested-elt (buffer-local-value 'agent-shell--state shown) '(:session :id)))))
                (accept-process-output nil 0.02)))
            (should (equal "fixture-new-session" (map-nested-elt (buffer-local-value 'agent-shell--state shown) '(:session :id))))
            (with-temp-buffer
              (insert-file-contents log)
              (let* ((requests (mapcar (lambda (line) (json-parse-string line :object-type 'alist)) (split-string (buffer-string) "\n" t)))
                     (loaded (seq-find (lambda (r) (equal (alist-get 'method r) "session/load")) requests)))
                (should (equal agent-sidebar-codex-home (map-nested-elt (car requests) '(fixture_environment codex_home))))
                (should (equal codex-test--id (map-nested-elt loaded '(params sessionId))))
                (should (equal root (file-name-as-directory (map-nested-elt loaded '(params cwd)))))))
            (message "Codex agent-shell client: session/load, session/new, reuse, cwd, and native-rollout ownership passed"))
        (dolist (shell shells)
          (when (buffer-live-p shell)
            (with-current-buffer shell (setq-local kill-buffer-query-functions nil) (kill-buffer shell))))))))
