;;; torvalds-tests.el --- Round 2 process-boundary probes -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'agent-sidebar)
(require 'acp)
(defconst torvalds-r2--fixture
  (expand-file-name "torvalds-fixture.py" (file-name-directory load-file-name)))

(defmacro torvalds-r2--fixture (&rest body)
  (declare (indent 0))
  `(let* ((temporary (make-temp-file "torvalds-r2-" t))
          (directory (file-name-as-directory temporary))
          (before (buffer-list)) processes)
     (unwind-protect
         (save-window-excursion ,@body)
       (dolist (process processes)
         (when (process-live-p process) (delete-process process)))
       (dolist (buffer (buffer-list))
         (unless (memq buffer before)
           (when-let* ((process (get-buffer-process buffer)))
             (set-process-query-on-exit-flag process nil)
             (when (process-live-p process) (delete-process process)))
           (when (buffer-live-p buffer)
             (with-current-buffer buffer (setq-local kill-buffer-query-functions nil))
             (kill-buffer buffer))))
       (delete-directory temporary t))))

(ert-deftest torvalds-r2-interleaved-wrappers-preserve-home-at-os-boundary ()
  "Start local ACP children after interleaved wrapping and ambient mutation."
  (torvalds-r2--fixture
    (let* ((home-a (expand-file-name "home-a/" temporary))
           (home-b (expand-file-name "home-b/" temporary))
           (log-a (expand-file-name "a.json" temporary))
           (log-b (expand-file-name "b.json" temporary))
           (log nil)
           (base-env '("CODEX_HOME=/wrong-config" "SIDEBAR_REVIEW_TAG=preserved"))
           (base `((:client-maker . ,(lambda (buffer)
                                      (acp-make-client :context-buffer buffer
                                                       :command (executable-find "python3")
                                                       :command-params (list torvalds-r2--fixture log)
                                                       :environment-variables base-env)))))
           (first (agent-sidebar--codex-session-config base home-a))
           ;; Rewrapping must replace the previous home and avoid nested wrappers.
           (second (agent-sidebar--codex-session-config first home-b))
           (process-environment (cons "CODEX_HOME=/wrong-ambient" process-environment)))
      (make-directory home-a) (make-directory home-b)
      (should (eq (agent-sidebar--codex-base-config second) base))
      (dolist (item (list (list first home-a log-a) (list second home-b log-b)))
        (setq log (nth 2 item))
        (let* ((config (nth 0 item)) (home (nth 1 item))
               (buffer (generate-new-buffer " *torvalds-r2-acp*"))
               (client (funcall (map-elt config :client-maker) buffer)))
          (with-current-buffer buffer
            (setq default-directory directory)
            (acp--start-client :client client))
          (push (map-elt client :process) processes)
          (let ((deadline (+ (float-time) 5)))
            (while (and (not (file-exists-p log)) (< (float-time) deadline))
              (accept-process-output nil 0.01)))
          (should (file-exists-p log))
          (with-temp-buffer
            (insert-file-contents log)
            (let ((actual (json-parse-buffer :object-type 'alist)))
              (should (equal (alist-get 'home actual) home))
              (should (equal (alist-get 'tag actual) "preserved"))
              (should (file-equal-p (alist-get 'cwd actual) directory))))))
      (should (equal base-env '("CODEX_HOME=/wrong-config" "SIDEBAR_REVIEW_TAG=preserved")))
      (message "ACP-INTERLEAVE: two real children kept distinct selected homes and inherited unrelated configuration"))))

(ert-deftest torvalds-r2-display-error-does-not-leave-unowned-terminal-children ()
  "Fault-inject display failure after real term process creation."
  (torvalds-r2--fixture
    (let* ((agent-sidebar-terminal-function nil)
           (entry (list :provider 'claude-cli :id (expand-file-name "rollout.jsonl" temporary)))
           (meta (list :session-id "12345678-1111-7111-8111-111111111111" :cwd directory))
           (make-term-original (symbol-function 'make-term)) buffers)
      (cl-letf (((symbol-function 'ghostel-exec) nil)
                ((symbol-function 'vterm) nil)
                ((symbol-function 'agent-sidebar--ensure-parsed) (lambda (_) meta))
                ((symbol-function 'agent-shell-sidebar--pop-to)
                 (lambda (_) (error "Injected display failure after child creation")))
                ((symbol-function 'make-term)
                 (lambda (&rest args)
                   (let ((buffer (apply make-term-original args)))
                     (push buffer buffers)
                     (push (get-buffer-process buffer) processes)
                     (set-process-query-on-exit-flag (car processes) nil)
                     buffer))))
        (dotimes (_ 2)
          (should-error
           (agent-sidebar--visit-terminal entry "review" "/bin/sh" '("-c" "exec sleep 30" "fixture"))))
        (let ((live (seq-filter #'process-live-p processes)))
          (message "DISPLAY-FAILURE: failed activations=2, live children=%d, session markers=%S"
                   (length live)
                   (mapcar (lambda (buffer)
                             (and (buffer-live-p buffer)
                                  (buffer-local-value 'agent-sidebar--terminal-session buffer))) buffers))
          (should-not live))))))
