;;; workflow-tests.el --- Command fix regressions -*- lexical-binding: t; -*-
(load (expand-file-name "../round-1/contrarian-workflow-tests.el" (file-name-directory load-file-name)) nil t)

(ert-deftest fix-workflow-mixed-provider-group-requires-row ()
  (codex-test--fixture
    (codex-test--write agent-sidebar-codex-home root)
    (merge--json-file root store "claude")
    (agent-sidebar-refresh) (merge--drain)
    (agent-sidebar-set-grouping '(repo))
    (goto-char (point-min))
    (cl-letf (((symbol-function 'agent-sidebar--launch-terminal)
               (lambda (&rest _) (ert-fail "Ambiguous group launched terminal")))
              ((symbol-function 'agent-shell-sidebar--start)
               (lambda (&rest _) (ert-fail "Ambiguous group launched agent-shell"))))
      (should-error (agent-sidebar-new-session) :type 'user-error))))

(ert-deftest fix-workflow-group-keeps-captured-home-and-prefix-codex-agent ()
  (codex-test--fixture
    (let ((captured-home agent-sidebar-codex-home) call)
      (codex-test--write agent-sidebar-codex-home root)
      (agent-sidebar-refresh) (merge--drain)
      (agent-sidebar-set-grouping '(repo model))
      (goto-char (point-min))
      (let ((agent-sidebar-codex-home (expand-file-name "changed-setting/" temporary)))
        (cl-letf (((symbol-function 'agent-sidebar--codex-start-agent-shell)
                   (lambda (directory &optional id)
                     (setq call (list directory id agent-sidebar-codex-home)) buffer))
                  ((symbol-function 'agent-shell-sidebar--pop-to) #'ignore))
          (agent-sidebar-new-session t)))
      (should (equal call (list root nil captured-home))))))

(ert-deftest fix-workflow-group-with-multiple-codex-homes-requires-row ()
  (codex-test--fixture
    (let ((agent-sidebar-providers (copy-tree agent-sidebar-providers))
          (other-home (expand-file-name "other-home/" temporary)) entries)
      (codex-test--write agent-sidebar-codex-home root)
      (setq entries (agent-sidebar--codex-list))
      (let ((agent-sidebar-codex-home other-home))
        (codex-test--write agent-sidebar-codex-home root)
        (setq entries (append entries (agent-sidebar--codex-list))))
      (let ((provider (copy-sequence (alist-get 'codex-cli agent-sidebar-providers))))
        (setq provider (plist-put provider :list (lambda () entries)))
        (agent-sidebar-register-provider provider))
      (agent-sidebar-refresh) (merge--drain)
      (agent-sidebar-set-grouping '(repo))
      (goto-char (point-min))
      (cl-letf (((symbol-function 'agent-sidebar--launch-terminal)
                 (lambda (&rest _) (ert-fail "Ambiguous Codex home launched"))))
        (should-error (agent-sidebar-new-session) :type 'user-error)))))

(ert-deftest fix-workflow-agent-shell-group-keeps-codex-agent ()
  (codex-test--fixture
    (merge--markdown root "codex" codex-test--id "Codex")
    (agent-sidebar-refresh) (merge--drain)
    (agent-sidebar-set-grouping '(repo model))
    (goto-char (point-min))
    (let (selected started)
      (cl-letf (((symbol-function 'agent-shell-sidebar--select-config)
                 (lambda (name) (setq selected name) 'chosen-config))
                ((symbol-function 'agent-shell-sidebar--start)
                 (lambda (directory config &rest _)
                   (setq started (list directory config)) buffer))
                ((symbol-function 'agent-shell-sidebar--pop-to) #'ignore))
        (agent-sidebar-new-session))
      (should (equal selected "Codex"))
      (should (equal started (list root 'chosen-config))))))

(ert-deftest fix-workflow-new-rejects-removed-display-entry ()
  (codex-test--fixture
    (let ((file (codex-test--write agent-sidebar-codex-home root)))
      (agent-sidebar-refresh) (merge--drain) (merge--goto file)
      (remhash file agent-sidebar--entries)
      (cl-letf (((symbol-function 'agent-sidebar--launch-terminal)
                 (lambda (&rest _) (ert-fail "Removed row launched"))))
        (should-error (agent-sidebar-new-session) :type 'user-error)))))

(ert-deftest fix-workflow-actions-abort-on-reentrant-provider-replacement ()
  (dolist (action '(agent-sidebar-visit agent-sidebar-visit-in-agent-shell agent-sidebar-new-session))
    (codex-test--fixture
      (let* ((file (codex-test--write agent-sidebar-codex-home root))
             (original (symbol-function 'agent-sidebar--codex-parse))
             (agent-sidebar-providers (copy-tree agent-sidebar-providers)))
        (agent-sidebar-refresh) (merge--goto file)
        (cl-letf (((symbol-function 'agent-sidebar--require-codex-terminal) #'ignore)
                  ((symbol-function 'agent-sidebar--launch-terminal)
                   (lambda (&rest _) (ert-fail "Obsolete provider launched terminal")))
                  ((symbol-function 'agent-sidebar--codex-start-agent-shell)
                   (lambda (&rest _) (ert-fail "Obsolete provider launched agent-shell")))
                  ((symbol-function 'agent-sidebar--codex-parse)
                   (lambda (entry)
                     (prog1 (funcall original entry)
                       (let ((replacement (copy-sequence (alist-get 'codex-cli agent-sidebar-providers))))
                         (agent-sidebar-register-provider replacement))))))
          (should-error (funcall action) :type 'user-error))))))

(ert-deftest fix-workflow-new-aborts-on-reentrant-owner-change ()
  (codex-test--fixture
    (let* ((file (codex-test--write agent-sidebar-codex-home root))
           (original (symbol-function 'agent-sidebar--codex-parse))
           (other (generate-new-buffer " *workflow changed owner*")))
      (unwind-protect
          (progn
            (agent-sidebar-refresh) (merge--goto file)
            (cl-letf (((symbol-function 'agent-sidebar--launch-terminal)
                       (lambda (&rest _) (ert-fail "Changed owner launched")))
                      ((symbol-function 'agent-sidebar--codex-parse)
                       (lambda (entry)
                         (prog1 (funcall original entry) (set-buffer other)))))
              (should-error (agent-sidebar-new-session) :type 'user-error)))
        (kill-buffer other)))))
