;;; scale.el --- Measure all callback work for the merged view -*- lexical-binding: t; -*-
(load (expand-file-name "tests.el" (file-name-directory load-file-name)) nil t)
(ert-delete-all-tests)

(ert-deftest merge-scale-3000-mixed-provider-files ()
  (merge--fixture
    (dotimes (i 1500)
      (merge--markdown root (format "md-%04d" i) (format "md-%d" i))
      (merge--json-file root store (format "cli-%04d" i)))
    (let ((parse (symbol-function 'agent-sidebar--parse-file))
          (collect (symbol-function 'agent-sidebar--collect))
          (render (symbol-function 'agent-sidebar--render-entry-row))
          (publish (symbol-function 'agent-shell-sidebar--publish-render))
          (reads 0) (scans 0) (rows 0) (publications 0) (progressive 0)
          times initial started)
      (cl-letf (((symbol-function 'agent-sidebar--parse-file)
                 (lambda (&rest args) (cl-incf reads) (apply parse args)))
                ((symbol-function 'agent-sidebar--collect)
                 (lambda () (cl-incf scans) (funcall collect)))
                ((symbol-function 'agent-sidebar--render-entry-row)
                 (lambda (&rest args) (cl-incf rows) (apply render args)))
                ((symbol-function 'agent-shell-sidebar--publish-render)
                 (lambda ()
                   (cl-incf publications)
                   (when agent-sidebar--parse-queue (cl-incf progressive))
                   (funcall publish))))
        (setq started (float-time))
        (agent-sidebar-refresh)
        (setq initial (- (float-time) started))
        (while (timerp agent-sidebar--parse-timer)
          (setq started (float-time))
          (timer-event-handler agent-sidebar--parse-timer)
          (push (- (float-time) started) times))
        (should (= reads 3000))
        (should (= scans 1))
        (should (= (length (merge--rows)) 3000))
        (should (> progressive 0))
        (should-not agent-shell-sidebar--render-error)
        (message "MERGE-SCALE %S"
                 (list :files 3000 :reads reads :scans scans :rows-built rows
                       :callbacks (length times) :publications publications
                       :publications-while-parsing progressive
                       :initial-refresh-ms (* initial 1000)
                       :all-callback-work-ms (* (apply #'+ times) 1000)
                       :total-work-ms (* (+ initial (apply #'+ times)) 1000)
                       :max-callback-ms (* (apply #'max times) 1000)))))))
