;;; tests.el --- Provider merge checks -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'agent-sidebar)

(defun merge--markdown (root name &optional session agent)
  (let ((file (expand-file-name (format ".agent-shell/transcripts/%s.md" name) root)))
    (make-directory (file-name-directory file) t)
    (with-temp-file file
      (insert (format "**Agent:** %s\n**Working Directory:** %s\n**Started:** 2026-09-08 12:00:00\n**Session ID:** %s\n**Model:** shell-model\n---\n## User\n\nPrompt %s\n"
                      (or agent "Claude") root (or session "") name))) file))
(defun merge--json-file (root store name &optional records)
  (let ((file (expand-file-name (concat (agent-sidebar--claude-encode-path root) "/" name ".jsonl") store)))
    (make-directory (file-name-directory file) t)
    (with-temp-file file
      (dolist (record (or records
                          `(((type . "user") (sessionId . ,name) (cwd . ,root)
                             (timestamp . "2026-09-08T19:00:00Z")
                             (isMeta . :json-false) (message . ((content . "CLI prompt") (role . "user"))))
                            ((type . "assistant") (message . ((model . "cli-model") (content . "answer")))))))
        (insert (json-encode record) "\n"))) file))
(defmacro merge--fixture (&rest body)
  (declare (indent 0))
  `(let* ((temporary (file-name-as-directory (make-temp-file "agent-sidebar-merge-" t)))
          (root (expand-file-name "repo-with space/" temporary))
          (store (expand-file-name "claude/" temporary))
          (agent-sidebar-extra-project-roots (list root))
          (agent-sidebar-claude-cli-projects-dir store)
          (agent-sidebar-enabled-providers '(agent-shell claude-cli))
          (agent-sidebar-grouping '(package repo model))
          (agent-sidebar-refresh-timer nil)
          (agent-sidebar-name " *merged sidebar test*")
          (agent-shell-sidebar--timer-buffers nil)
          (post-command-hook nil)
          (projectile-known-projects nil)
          (default-directory root)
          (buffer (generate-new-buffer " *merge fixture*")))
     (make-directory root t)
     (unwind-protect
         (cl-letf (((symbol-function 'project-known-project-roots) (lambda () nil))
                   ((symbol-function 'agent-shell-buffers) (lambda () nil))
                   ((symbol-function 'input-pending-p) (lambda () nil)))
                  (with-current-buffer buffer (agent-sidebar-mode) ,@body))
       (when (buffer-live-p buffer) (kill-buffer buffer))
       (when-let* ((sidebar (get-buffer agent-sidebar-name))) (kill-buffer sidebar))
       (delete-directory temporary t))))
(defun merge--drain ()
  (let ((ticks 0))
    (while (and (timerp agent-sidebar--parse-timer) (< ticks 1000))
      (timer-event-handler agent-sidebar--parse-timer)
      (cl-incf ticks))
    (should (< ticks 1000))
    (should-not agent-sidebar--parse-queue)
    (should-not agent-shell-sidebar--render-iterator)
    (should-not agent-shell-sidebar--render-dirty)
    (should-not agent-shell-sidebar--render-error)
    ticks))
(defun merge--goto (file)
  (goto-char (point-min))
  (while (and (not (eobp)) (not (equal file (get-text-property (point) 'agent-shell-sidebar-file))))
    (forward-line 1))
  (should-not (eobp)))
(defun merge--rows ()
  (let (files)
    (save-excursion
      (goto-char (point-min))
      (while (not (eobp))
        (when-let* ((file (get-text-property (point) 'agent-shell-sidebar-file))) (push file files))
        (forward-line 1)))
    (nreverse files)))

(ert-deftest merge-two-providers-metadata-model-and-nesting ()
  (merge--fixture
    (let ((md (merge--markdown root "one" "md-session"))
          (json (merge--json-file root store "cli-session")))
      (agent-sidebar-refresh)
      (should (= (length agent-sidebar--parse-queue) 2))
      (should (= (length (merge--rows)) 2))
      (merge--drain)
      (should (string-search "agent-shell (1)" (buffer-string)))
      (should (string-search "Claude CLI (1)" (buffer-string)))
      (should (string-search "shell-model (1)" (buffer-string)))
      (should (string-search "cli-model (1)" (buffer-string)))
      (should (string-search "CLI prompt" (buffer-string)))
      (should (equal (sort (list md json) #'string<) (sort (merge--rows) #'string<))))))

(ert-deftest merge-flat-date-filter-and-fold-preserve-marks ()
  (merge--fixture
    (let ((md (merge--markdown root "one" "session")))
      (merge--json-file root store "cli")
      (agent-sidebar-refresh) (merge--drain)
      (merge--goto md) (end-of-line) (agent-sidebar-mark-delete)
      (agent-sidebar-set-grouping nil)
      (should (= 2 (length (merge--rows))))
      (should-not (text-property-search-forward 'agent-sidebar-group nil (lambda (_ value) value)))
      (agent-sidebar-set-filter "shell-model")
      (should (equal (merge--rows) (list md)))
      (should (eq (gethash md agent-sidebar--marks) 'delete))
      (agent-sidebar-set-grouping '(date repo))
      (goto-char (point-min)) (end-of-line) (agent-sidebar-toggle-group)
      (should-not (merge--rows))
      (agent-sidebar-toggle-group)
      (should (equal (merge--rows) (list md)))
      (should-error (agent-sidebar-set-grouping '(repo repo)) :type 'user-error))))

(ert-deftest merge-jsonl-skips-meta-and-tools-and-reads-later-model ()
  (merge--fixture
    (let* ((records `(((type . "user") (isMeta . t) (message . ((content . "meta"))))
                      ((type . "user") (message . ((content . "<command-name>ignore"))))
                      ((type . "user") (isMeta . :json-false) (cwd . ,root)
                       (timestamp . "2026-09-08T19:00:00Z")
                       (message . ((content . [((type . "tool_result") (content . "ignore"))
                                               ((type . "text") (text . "Actual prompt\nnext"))]))))
                      ((type . "assistant") (message . ((model . "later-model"))))))
           (file (merge--json-file root store "short" records)))
      (with-temp-buffer (insert "\nnot json\n") (write-region (point-min) (point-max) file t 'silent))
      (let ((meta (agent-sidebar--claude-parse (list :id file))))
        (should-not (plist-get meta :error))
        (should (equal (plist-get meta :preview) "Actual prompt"))
        (should (equal (plist-get meta :model) "later-model"))
        (should (equal (plist-get meta :cwd) root))))))

(ert-deftest merge-jsonl-read-is-bounded-and-preserves-complete-records ()
  (merge--fixture
    (let* ((file (merge--json-file root store "bound"))
           (prefix (json-encode '((type . "user") (message . ((content . "first")))))))
      (with-temp-file file
        (insert prefix "\n" (json-encode `((padding . ,(make-string 70000 ?x)))) "\n"
                "{\"cwd\":\"/wrong\"}\n"))
      (let ((meta (agent-sidebar--claude-parse (list :id file))))
        (should (equal (plist-get meta :preview) "first"))
        (should-not (plist-get meta :cwd)))
      (with-temp-file file (insert prefix))
      (should (equal (plist-get (agent-sidebar--claude-parse (list :id file)) :preview) "first")))))

(ert-deftest merge-jsonl-nonregular-and-read-errors-are-explicit ()
  (merge--fixture
    (let ((file (merge--json-file root store "pipe")))
      (delete-file file)
      (should (= 0 (call-process "mkfifo" nil nil nil file)))
      (should (plist-get (agent-sidebar--claude-parse (list :id file)) :error)))))

(ert-deftest merge-cache-rechecks-size-and-recovers-read-permissions ()
  (merge--fixture
    (let ((file (merge--json-file root store "mutable")))
      (agent-sidebar-refresh) (merge--drain)
      (let ((stamp (file-attribute-modification-time (file-attributes file))))
        (with-temp-file file (insert (json-encode `((type . "user") (cwd . ,root)
                                                    (message . ((content . "changed and longer prompt")))))))
        (set-file-times file stamp)
        (let ((meta (agent-sidebar--ensure-parsed (gethash file agent-sidebar--entries))))
          (should (equal (plist-get meta :preview) "changed and longer prompt"))))
      (set-file-modes file #o000)
      (remhash file agent-sidebar--parse-cache)
      (should-error (agent-sidebar--ensure-parsed (gethash file agent-sidebar--entries)))
      (set-file-modes file #o600)
      (agent-sidebar-refresh) (merge--drain)
      (should-not (plist-get (agent-sidebar--cached-meta (gethash file agent-sidebar--entries)) :error)))))

(ert-deftest merge-claude-directory-is-confirmed-not-guessed ()
  (merge--fixture
    (let ((file (merge--json-file root store "directory"))
          (agent-sidebar-extra-project-roots nil))
      (should-not (agent-sidebar--claude-decode-project-dir (agent-sidebar--claude-encode-path root)))
      (agent-sidebar-refresh) (merge--drain)
      (should (equal (agent-sidebar--entry-repo (gethash file agent-sidebar--entries)) root)))))

(ert-deftest merge-session-id-recovery-is-unambiguous-and-invalidates ()
  (merge--fixture
    (merge--json-file root store "first")
    (should (equal "first" (agent-sidebar--find-claude-session-for-transcript "Claude" root "2026-09-08T19:00:00Z")))
    (merge--json-file root store "second")
    (should-not (agent-sidebar--find-claude-session-for-transcript "Claude" root "2026-09-08T19:00:00Z"))
    (should-not (agent-sidebar--find-claude-session-for-transcript "Codex" root "2026-09-08T19:00:00Z"))))

(ert-deftest merge-shell-activation-uses-recovery-or-session-picker ()
  (merge--fixture
    (let* ((file (merge--markdown root "missing"))
           (config '((:mode-line-name . "Claude"))) calls)
      (agent-sidebar-refresh) (merge--drain)
      (cl-letf (((symbol-function 'agent-shell-sidebar--start)
                 (lambda (directory cfg &optional session strategy)
                   (push (list directory cfg session strategy) calls) buffer))
                ((symbol-function 'agent-shell-sidebar--pop-to) #'ignore)
                ((symbol-function 'agent-shell-sidebar--select-config) (lambda (_) config)))
        (agent-sidebar--agent-shell-visit (gethash file agent-sidebar--entries))
        (should (equal (car calls) (list root config nil 'prompt)))
        (merge--json-file root store "recovered")
        (agent-sidebar--agent-shell-visit (gethash file agent-sidebar--entries))
        (should (equal (car calls) (list root config "recovered" nil)))))))

(ert-deftest merge-terminal-arguments-directory-and-reuse ()
  (merge--fixture
    (let* ((file (merge--json-file root store "id"))
           (agent-sidebar-claude-cli-command "/bin/cat")
           (terminal (generate-new-buffer " *mock CLI terminal*"))
           (agent-sidebar-terminal-function
            (lambda (name program args directory)
              (should (stringp name)) (should (equal program "/bin/cat"))
              (should (equal args '("--resume" "id"))) (should (equal directory root))
              (with-current-buffer terminal
                (make-process :name "merge-local-process" :buffer terminal :command '("/bin/cat") :noquery t))
              terminal)))
      (unwind-protect
          (progn
            (agent-sidebar-refresh) (merge--drain)
            (cl-letf (((symbol-function 'agent-shell-sidebar--pop-to) #'ignore))
              (agent-sidebar--claude-visit (gethash file agent-sidebar--entries))
              (let ((agent-sidebar-terminal-function (lambda (&rest _) (ert-fail "Duplicate terminal"))))
                (agent-sidebar--claude-visit (gethash file agent-sidebar--entries))))
            (should (agent-sidebar--owned-file-p file)))
        (when-let* ((process (get-buffer-process terminal))) (delete-process process))
        (kill-buffer terminal)))))

(ert-deftest merge-term-fallback-preserves-argv-with-metacharacters ()
  (merge--fixture
    (let ((args '("a b" "$(touch never)" "q'x")) received target)
      (cl-letf (((symbol-function 'ghostel-exec) nil) ((symbol-function 'vterm) nil)
                ((symbol-function 'make-term)
                 (lambda (_name program _startfile &rest argv)
                   (setq received (list program argv) target (generate-new-buffer " *fake term*"))))
                ((symbol-function 'term-mode) #'ignore) ((symbol-function 'term-char-mode) #'ignore)
                ((symbol-function 'agent-shell-sidebar--pop-to) #'ignore))
        (unwind-protect
            (progn (agent-sidebar--launch-terminal "test" "/bin/cat" args root)
                   (should (equal received (list "/bin/cat" args))))
          (when target (kill-buffer target)))))))

(ert-deftest merge-progressive-tree-does-not-rediscover-and-bounds-rows ()
  (merge--fixture
    (let ((list-function (symbol-function 'agent-sidebar--agent-shell-list))
          (row-function (symbol-function 'agent-sidebar--render-entry-row))
          (agent-sidebar-enabled-providers '(agent-shell))
          (reads 0) (rows 0) (scans 0) (publications 0))
      (dotimes (i 420) (merge--markdown root (format "%04d" i) (format "s%d" i)))
      (cl-letf (((symbol-function 'agent-sidebar--agent-shell-list)
                 (lambda () (cl-incf scans) (funcall list-function)))
                ((symbol-function 'agent-sidebar--render-entry-row)
                 (lambda (&rest args) (cl-incf rows) (apply row-function args))))
        (agent-sidebar-refresh)
        (should (= scans 1))
        (while agent-sidebar--parse-timer
          (setq rows 0)
          (timer-event-handler agent-sidebar--parse-timer)
          (should (<= rows 300))
          (when (and agent-sidebar--parse-queue (string-search "Prompt " (buffer-string)))
            (cl-incf publications)))
        (setq reads (hash-table-count agent-sidebar--parse-cache))
        (should (= reads 420)) (should (> publications 0)) (should (= scans 1))
        (should (= (length (merge--rows)) 420))
        (should-not agent-shell-sidebar--render-error)
        (message "Provider tree: %d reads, %d scan, progressive publication observed" reads scans)))))

(ert-deftest merge-reentrant-refresh-does-not-lose-provider-entry ()
  (merge--fixture
    (merge--markdown root "original" "old")
    (agent-sidebar-refresh)
    (let ((triggered nil) fresh)
      (let ((after-insert-file-functions
             (list (lambda (_)
                     (unless triggered
                       (setq triggered t fresh (merge--json-file root store "fresh"))
                       (with-current-buffer buffer (agent-sidebar-refresh))) nil))))
        (timer-event-handler agent-sidebar--parse-timer))
      (merge--drain)
      (should (member fresh (merge--rows)))
      (should (string-search "CLI prompt" (buffer-string))))))

(ert-deftest merge-provider-error-keeps-old-snapshot-and-work ()
  (merge--fixture
    (merge--markdown root "old" "old")
    (agent-sidebar-refresh)
    (let ((timer agent-sidebar--parse-timer) (entries agent-sidebar--entries)
          (agent-sidebar-enabled-providers '(missing)))
      (should-error (agent-sidebar-refresh))
      (should (eq entries agent-sidebar--entries))
      (should (eq timer agent-sidebar--parse-timer)))
    (merge--drain)))

(ert-deftest merge-provider-replacement-invalidates-cached-metadata ()
  (merge--fixture
    (let* ((file (merge--markdown root "custom" "id"))
           (agent-sidebar-providers (copy-tree agent-sidebar-providers))
           (agent-sidebar-enabled-providers '(custom))
           (lister (lambda () (list (list :id file))))
           (one (lambda (_) '(:preview "first parser")))
           (two (lambda (_) '(:preview "second parser"))))
      (agent-sidebar-register-provider (list :id 'custom :name "Custom" :list lister :parse one :visit #'ignore))
      (agent-sidebar-refresh) (merge--drain)
      (should (string-search "first parser" (buffer-string)))
      (agent-sidebar-register-provider (list :id 'custom :name "Custom" :list lister :parse two :visit #'ignore))
      (agent-sidebar-refresh)
      (should (equal (list file) agent-sidebar--parse-queue))
      (merge--drain)
      (should (string-search "second parser" (buffer-string)))
      (should-not (string-search "first parser" (buffer-string))))))

(ert-deftest merge-provider-collision-does-not-publish-partial-discovery ()
  (merge--fixture
    (let* ((file (merge--markdown root "same" "id"))
           (agent-sidebar-providers (copy-tree agent-sidebar-providers)))
      (agent-sidebar-refresh)
      (agent-sidebar-register-provider
       (list :id 'duplicate :name "Duplicate" :list (lambda () (list (list :id file)))
             :parse #'ignore :visit #'ignore))
      (let ((entries agent-sidebar--entries) (timer agent-sidebar--parse-timer)
            (agent-sidebar-enabled-providers '(agent-shell duplicate)))
        (should-error (agent-sidebar-refresh) :type 'user-error)
        (should (eq entries agent-sidebar--entries))
        (should (eq timer agent-sidebar--parse-timer)))
      (merge--drain))))

(ert-deftest merge-jsonl-wrong-record-shapes-do-not-hide-valid-records ()
  (merge--fixture
    (let ((file (merge--json-file
                 root store "shapes"
                 '(((type . "user") (message . "bad shape"))
                   ((type . "user") (message . ((content . "real prompt"))))))))
      (with-temp-buffer
        (insert "true\n[]\n[1,2]\nnull\n42\n")
        (write-region (point-min) (point-max) file t 'silent))
      (should (equal "real prompt" (plist-get (agent-sidebar--claude-parse (list :id file)) :preview))))))

(ert-deftest merge-vterm-launch-keeps-dedicated-sidebar-and-quotes-argv ()
  (merge--fixture
    (save-window-excursion
      (let ((ordinary (selected-window))
            (sidebar (display-buffer-in-side-window buffer '((side . left))))
            (args '("--resume" "space ' and $(text)")) target)
        (unwind-protect
            (progn
              (set-window-dedicated-p sidebar t)
              (select-window sidebar)
              (cl-letf (((symbol-function 'ghostel-exec) nil)
                        ((symbol-function 'vterm)
                         (lambda (name)
                           (should (eq ordinary (selected-window)))
                           (should (equal vterm-shell
                                          (mapconcat #'shell-quote-argument (cons "/bin/cat" args) " ")))
                           (should (equal default-directory root))
                           (setq target (generate-new-buffer name))
                           (pop-to-buffer-same-window target)
                           target)))
                (should (eq (agent-sidebar--launch-terminal " *merge vterm*" "/bin/cat" args root) target)))
              (should (eq (window-buffer sidebar) buffer))
              (should (window-dedicated-p sidebar))
              (should (eq (window-buffer ordinary) target)))
          (when target (kill-buffer target)))))))

(ert-deftest merge-ghostel-dispatch-and-failed-start-cleanup ()
  (merge--fixture
    (let (target)
      (cl-letf (((symbol-function 'ghostel-exec)
                 (lambda (buf program args)
                   (setq target buf)
                   (should (eq (current-buffer) buf))
                   (should (equal default-directory root))
                   (should (equal program "/bin/cat"))
                   (should (equal args '("two words")))
                   (error "Module unavailable"))))
        (should-error (agent-sidebar--launch-terminal " *merge ghostel*" "/bin/cat" '("two words") root))
        (should-not (buffer-live-p target))))))

(ert-deftest merge-terminal-ownership-prevents-delete-until-process-exits ()
  (merge--fixture
    (let* ((file (merge--json-file root store "owned"))
           (alias (expand-file-name "alias.jsonl" temporary))
           (terminal (generate-new-buffer " *merge owner*"))
           (delete-by-moving-to-trash nil))
      (make-symbolic-link file alias)
      (unwind-protect
          (progn
            (with-current-buffer terminal
              (make-process :name "merge-owner" :buffer terminal :command '("/bin/cat") :noquery t)
              (setq-local agent-sidebar--terminal-file alias))
            (agent-sidebar-refresh) (merge--drain)
            (merge--goto file) (agent-sidebar-mark-delete)
            (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
              (agent-sidebar-execute)
              (should (file-exists-p file))
              (should (eq (gethash file agent-sidebar--marks) 'delete))
              (delete-process (get-buffer-process terminal))
              (agent-sidebar-execute)
              (should-not (file-exists-p file))
              (should-not (gethash file agent-sidebar--marks))))
        (when-let* ((process (get-buffer-process terminal))) (delete-process process))
        (kill-buffer terminal)))))

(ert-deftest merge-buffer-isolation-and-legacy-buffer-upgrade ()
  (merge--fixture
    (merge--markdown root "one" "id")
    (agent-sidebar-refresh)
    (let ((old (get-buffer-create agent-sidebar-name))
          (cache agent-sidebar--parse-cache) (timer agent-sidebar--parse-timer))
      (with-current-buffer old
        (agent-shell-sidebar-mode)
        (puthash "preserved mark" 'delete agent-shell-sidebar--marks)
        (setq agent-shell-sidebar--filter "preserved filter"))
      (should (eq old (agent-sidebar--get-or-create-buffer)))
      (with-current-buffer old
        (should (derived-mode-p 'agent-sidebar-mode))
        (should (eq (gethash "preserved mark" agent-sidebar--marks) 'delete))
        (should (equal "preserved filter" agent-sidebar--filter))
        (should-not (eq cache agent-sidebar--parse-cache))
        (should (eq (key-binding (kbd "RET")) 'agent-sidebar-visit))
        (should (eq (key-binding (kbd "G")) 'agent-sidebar-set-grouping)))
      (kill-buffer old)
      (should (eq timer agent-sidebar--parse-timer))
      (merge--drain)
      (should (string-search "Prompt one" (buffer-string))))))

(defconst merge--argv-fixture
  (expand-file-name "argv-fixture.py" (file-name-directory (or load-file-name buffer-file-name))))

(ert-deftest merge-real-term-process-receives-exact-argv-and-cwd ()
  (merge--fixture
    (let* ((output (expand-file-name "arguments.json" temporary))
           (program (executable-find "python3"))
           (args '("two words" "x'y" "$(never-execute)")) target)
      (should program)
      (cl-letf (((symbol-function 'ghostel-exec) nil) ((symbol-function 'vterm) nil)
                ((symbol-function 'agent-shell-sidebar--pop-to) #'ignore))
        (unwind-protect
            (progn
              (setq target (agent-sidebar--launch-terminal
                            "merge argv" program (append (list merge--argv-fixture output) args) root))
              (let ((process (get-buffer-process target)) (deadline (+ (float-time) 5)))
                (while (and (process-live-p process) (< (float-time) deadline))
                  (accept-process-output process 0.05))
                (should (= (process-exit-status process) 0)))
              (with-temp-buffer
                (insert-file-contents output)
                (let ((data (json-parse-buffer :object-type 'alist :array-type 'list)))
                  (should (equal (alist-get 'argv data) args))
                  (should (equal (file-truename (alist-get 'cwd data))
                                 (directory-file-name (file-truename root)))))))
          (when (buffer-live-p target)
            (when-let* ((process (get-buffer-process target))) (delete-process process))
            (kill-buffer target)))))))
